import { TranslationKeys } from './types';

const ar: TranslationKeys = {
  common: {
    loading: 'جاري التحميل...',
    error: 'حدث خطأ',
    retry: 'إعادة المحاولة',
    cancel: 'إلغاء',
    save: 'حفظ',
    delete: 'حذف',
    edit: 'تعديل',
    search: 'بحث',
    noResults: 'لا توجد نتائج',
    confirm: 'تأكيد',
    yes: 'نعم',
    no: 'لا',
    ok: 'حسناً',
    done: 'تم',
    next: 'التالي',
    back: 'رجوع',
    close: 'إغلاق',
    share: 'مشاركة',
    refresh: 'تحديث',
    seeAll: 'عرض الكل',
    showMore: 'عرض المزيد',
    showLess: 'عرض أقل',
    stay: 'البقاء',
    discard: 'تجاهل',
    saveChanges: 'حفظ التغييرات',
    remove: 'إزالة',
    comingSoon: 'قريباً',
    comingSoonMessage: '{{feature}} قريباً!',
    item: 'عنصر',
    items: 'عناصر',
    keep: 'إبقاء',
    options: 'خيارات',
    restore: 'استعادة',
    continue: 'متابعة',
  },
  auth: {
    loginOrSignup: 'تسجيل الدخول أو إنشاء حساب',
    emailPlaceholder: 'أدخل بريدك الإلكتروني',
    emailLabel: 'البريد الإلكتروني',
    passwordPlaceholder: 'أدخل كلمة المرور',
    passwordLabel: 'كلمة المرور',
    namePlaceholder: 'أدخل اسمك الكامل',
    nameLabel: 'الاسم',
    continue: 'متابعة',
    createAccount: 'إنشاء حساب',
    welcomeBack: 'مرحباً بعودتك',
    signIn: 'تسجيل الدخول',
    signOut: 'تسجيل الخروج',
    signOutConfirmTitle: 'تسجيل الخروج',
    signOutConfirmMessage: 'هل أنت متأكد من تسجيل الخروج؟',
    forgotPassword: 'نسيت كلمة المرور؟',
    orContinueWith: 'أو المتابعة عبر',
    verifyEmail: 'تأكيد البريد الإلكتروني',
    verifyEmailSubtitle: 'أرسلنا رمز تحقق مكون من 6 أرقام إلى',
    enterCode: 'أدخل الرمز',
    resendCode: 'إعادة إرسال الرمز',
    codeSent: 'تم إرسال رمز تحقق جديد إلى بريدك الإلكتروني.',
    codeExpired: 'انتهت صلاحية رمز التحقق. يرجى طلب رمز جديد.',
    invalidCode: 'رمز التحقق الذي أدخلته غير صحيح.',
    emailVerified: 'تم تأكيد البريد الإلكتروني!',
    emailVerifiedSubtitle: 'تم تأكيد بريدك الإلكتروني بنجاح. يمكنك الآن البدء في استخدام سوق جاري.',
    getStarted: 'ابدأ الآن',
    passwordReset: 'تم إعادة تعيين كلمة المرور!',
    passwordResetSubtitle: 'تم إعادة تعيين كلمة المرور بنجاح. يمكنك الآن تسجيل الدخول بكلمة المرور الجديدة.',
    newPassword: 'كلمة المرور الجديدة',
    newPasswordPlaceholder: 'أنشئ كلمة مرور جديدة',
    setNewPassword: 'تعيين كلمة المرور الجديدة',
    passwordRequirements: {
      title: 'يجب أن تحتوي كلمة المرور على:',
      minLength: '6 أحرف على الأقل',
      uppercase: 'حرف كبير واحد',
      lowercase: 'حرف صغير واحد',
      number: 'رقم واحد',
    },
    oauthError: 'حدثت مشكلة في تسجيل الدخول. يرجى المحاولة مرة أخرى.',
    signInMethod: 'طريقة تسجيل الدخول',
    signInMethodMessage: 'تم إنشاء هذا الحساب باستخدام {{provider}}. يرجى استخدام زر {{provider}} لتسجيل الدخول.',
    noAccountSignUp: 'ليس لديك حساب؟ سجّل الآن',
    currentPassword: 'كلمة المرور الحالية',
    currentPasswordPlaceholder: 'أدخل كلمة المرور الحالية',
    newPasswordPlaceholder: 'أدخل كلمة المرور الجديدة',
    confirmNewPassword: 'تأكيد كلمة المرور الجديدة',
    confirmNewPasswordPlaceholder: 'تأكيد كلمة المرور الجديدة',
    passwordMinLength: 'يجب أن تكون كلمة المرور 6 أحرف على الأقل',
    updatePassword: 'تحديث كلمة المرور',
    passwordUpdated: 'تم تحديث كلمة المرور.',
    currentPasswordIncorrect: 'كلمة المرور الحالية غير صحيحة.',
    passwordsDoNotMatch: 'كلمتا المرور الجديدتان غير متطابقتين.',
    cannotChangePassword: 'لا يمكن تغيير كلمة المرور',
    cannotChangePasswordMessage: 'قمت بتسجيل الدخول عبر Google أو Facebook. لتعيين كلمة مرور، يرجى استخدام خيار "نسيت كلمة المرور" في شاشة تسجيل الدخول.',
  },
  tabs: {
    home: 'الرئيسية',
    chats: 'المحادثات',
    post: 'إعلان جديد',
    favorites: 'المفضلة',
    myListings: 'إعلاناتي',
  },
  home: {
    greeting: 'مرحباً بك في سوق جاري',
    searchPlaceholder: 'ابحث في الإعلانات...',
    categories: 'الفئات',
    recentlyViewed: 'شوهد مؤخراً',
    noRecentlyViewed: 'لا توجد مشاهدات مؤخراً',
    noRecentlyViewedSubtext: 'الإعلانات التي تشاهدها ستظهر هنا',
    clearRecentlyViewed: 'مسح',
    browseListings: 'تصفح الإعلانات',
  },
  categories: {
    // Main categories
    buySell: 'بيع وشراء',
    cars: 'سيارات',
    realEstate: 'عقارات',
    jobs: 'وظائف',
    services: 'خدمات',
    pets: 'حيوانات أليفة',
    // Buy & Sell subcategories
    electronics: 'إلكترونيات',
    furniture: 'أثاث',
    clothing: 'ملابس',
    books: 'كتب',
    phones: 'هواتف',
    computers: 'حواسيب',
    homeAppliances: 'أجهزة منزلية',
    toysGames: 'ألعاب',
    sportsEquipment: 'معدات رياضية',
    // Cars subcategories
    carsTrucks: 'سيارات وشاحنات',
    motorcycles: 'دراجات نارية',
    vehicleParts: 'قطع غيار',
    // Real Estate subcategories
    forRent: 'للإيجار',
    forSale: 'للبيع',
    // Jobs subcategories
    accounting: 'محاسبة',
    customerService: 'خدمة عملاء',
    healthcare: 'رعاية صحية',
    sales: 'مبيعات',
    itProgramming: 'تقنية وبرمجة',
    // Services subcategories
    homeMaintenance: 'صيانة منزلية',
    tutoring: 'دروس خصوصية',
    cleaning: 'تنظيف',
    moving: 'نقل',
    // Pets subcategories
    cats: 'قطط',
    dogs: 'كلاب',
    birds: 'طيور',
    // Common
    other: 'أخرى',
  },
  listings: {
    myListings: 'إعلاناتي',
    noListings: 'لا توجد إعلانات',
    noListingsSubtext: 'ابدأ البيع بإنشاء إعلانك الأول',
    noListingsSubtitle: 'ابدأ البيع بإنشاء إعلانك الأول',
    createFirst: 'أنشئ إعلانك الأول',
    createListing: 'إنشاء إعلان',
    active: 'نشط',
    sold: 'مباع',
    inactive: 'غير نشط',
    deleted: 'محذوف',
    all: 'الكل',
    markAsSold: 'تحديد كمباع',
    markAsActive: 'تحديد كنشط',
    deactivate: 'إلغاء التفعيل',
    restore: 'استعادة',
    deletePermanently: 'حذف نهائي',
    deleteConfirmTitle: 'إزالة الإعلان',
    deleteConfirmMessage: 'سيتم إخفاء الإعلان عن المشترين. يمكنك استعادته لاحقاً.',
    permanentDeleteConfirmTitle: 'حذف نهائي؟',
    permanentDeleteConfirmMessage: 'لا يمكن التراجع عن هذا الإجراء. سيتم حذف الإعلان نهائياً.',
    statusUpdated: 'تم تحديث حالة الإعلان',
    listingDeleted: 'تم حذف الإعلان',
    listingRestored: 'تم استعادة الإعلان',
    viewListing: 'عرض الإعلان',
    editListing: 'تعديل الإعلان',
    postedBy: 'نشر بواسطة',
    memberSince: 'عضو منذ',
    viewProfile: 'عرض الملف الشخصي',
    contactSeller: 'التواصل مع البائع',
    startChat: 'بدء محادثة',
    callSeller: 'اتصال',
    whatsappSeller: 'واتساب',
    price: 'السعر',
    free: 'مجاني',
    negotiable: 'قابل للتفاوض',
    location: 'الموقع',
    description: 'الوصف',
    noDescription: 'لا يوجد وصف',
    category: 'الفئة',
    posted: 'نُشر',
    updated: 'تم التحديث',
    views: 'مشاهدات',
    favorites: 'مفضلة',
    shareError: 'تعذر مشاركة الإعلان',
    // Sign in required
    signInRequired: 'تسجيل الدخول مطلوب',
    signInRequiredSubtitle: 'يرجى تسجيل الدخول لعرض إعلاناتك',
    // Filter tabs
    filterAll: 'الكل',
    filterActive: 'نشط',
    filterSold: 'مُباع',
    filterHidden: 'مخفي',
    // Empty state messages for filters
    noListingsInFilter: 'لا توجد إعلانات في هذا الفلتر',
    noActive: 'لا توجد إعلانات نشطة',
    noSold: 'لا توجد إعلانات مباعة',
    noInactive: 'لا توجد إعلانات مخفية',
    // Status badges
    statusActive: 'نشط',
    statusSold: 'مُباع',
    statusHidden: 'مخفي',
    statusUnavailable: 'غير متوفر',
    // Action buttons
    actionEdit: 'تعديل',
    actionMarkSold: 'تحديد كمُباع',
    actionRemove: 'إزالة',
    actionReactivate: 'إعادة تفعيل',
    actionRestore: 'استعادة',
    actionDeleteForever: 'حذف نهائي',
    // Confirmation dialogs
    removeConfirmTitle: 'إزالة الإعلان؟',
    removeConfirmMessage: 'سيتم إخفاء هذا الإعلان عن المشترين. يمكنك استعادته لاحقاً.',
    deleteForeverConfirmTitle: 'حذف نهائي؟',
    deleteForeverConfirmMessage: 'لا يمكن التراجع عن هذا الإجراء. سيتم حذف الإعلان نهائياً.',
    markSoldConfirmTitle: 'تحديد كمُباع؟',
    markSoldConfirmMessage: 'سيتم تحديد إعلانك كمُباع.',
    // Success/error messages
    listingRemoved: 'تم إزالة الإعلان',
    updateFailed: 'فشل التحديث. يرجى المحاولة مرة أخرى.',
  },
  chat: {
    messages: 'الرسائل',
    noConversations: 'لا توجد محادثات',
    noConversationsSubtext: 'ابدأ المحادثة مع البائعين بزيارة إعلان والضغط على "محادثة"',
    startChatting: 'ابدأ المحادثة',
    browseListings: 'تصفح الإعلانات',
    typeMessage: 'اكتب رسالة...',
    send: 'إرسال',
    sending: 'جاري الإرسال...',
    sent: 'تم الإرسال',
    delivered: 'تم التوصيل',
    read: 'مقروءة',
    voiceMessage: 'رسالة صوتية',
    holdToRecord: 'اضغط مطولاً للتسجيل',
    releaseToSend: 'أفلت للإرسال',
    recording: 'جاري التسجيل...',
    tapToPlay: 'اضغط للتشغيل',
    today: 'اليوم',
    yesterday: 'أمس',
    online: 'متصل',
    offline: 'غير متصل',
    typing: 'يكتب...',
    selectConversations: 'تحديد',
    deleteConversations: 'حذف',
    deleteConversationsConfirm: 'حذف {{count}} محادثة؟',
    signInRequired: 'تسجيل الدخول مطلوب',
    signInRequiredSubtext: 'يرجى تسجيل الدخول لعرض رسائلك',
    listingDeleted: 'تم حذف هذا الإعلان',
    listingUnavailable: 'الإعلان غير متوفر',
  },
  favorites: {
    favorites: 'المفضلة',
    noFavorites: 'لا توجد مفضلات',
    noFavoritesSubtext: 'احفظ الإعلانات التي تعجبك بالضغط على أيقونة القلب',
    browseNow: 'تصفح الآن',
    removeFavorite: 'إزالة',
    addFavorite: 'إضافة إلى المفضلة',
    signInRequired: 'تسجيل الدخول مطلوب',
    signInRequiredSubtext: 'يرجى تسجيل الدخول لعرض مفضلاتك',
    itemSold: 'تم البيع',
    itemUnavailable: 'غير متوفر',
    removeUnavailableMessage: 'هذا الإعلان لم يعد متاحاً. هل تريد إزالته من المفضلة؟',
  },
  post: {
    postListing: 'نشر إعلان',
    titlePlaceholder: 'العنوان...',
    titleLabel: 'عنوان الإعلان',
    selectCategory: 'اختر فئة',
    categorySelected: '{{subcategory}} ‹ {{category}}',
    continue: 'متابعة',
    missingTitle: 'يرجى إدخال عنوان لإعلانك',
    missingCategory: 'يرجى اختيار فئة',
  },
  productDetails: {
    listingDetails: 'تفاصيل الإعلان',
    description: 'الوصف',
    descriptionPlaceholder: 'صف المنتج بدقة...',
    price: 'السعر',
    pricePlaceholder: 'أدخل السعر',
    currency: 'العملة',
    location: 'الموقع',
    locationPlaceholder: 'اختر الموقع',
    selectLocation: 'اختر الموقع',
    photos: 'الصور',
    addPhotos: 'إضافة صور',
    photoLimit: '{{max}}/{{current}} صور',
    removePhoto: 'إزالة',
    contactInfo: 'معلومات التواصل',
    contactInfoSubtitle: 'أضف طريقة تواصل واحدة على الأقل للمشترين',
    phoneNumber: 'رقم الهاتف',
    phonePlaceholder: 'رقم الهاتف',
    whatsappNumber: 'رقم الواتساب',
    whatsappPlaceholder: 'رقم الواتساب',
    phoneWhatsappPlaceholder: 'الهاتف / الواتساب',
    sameAsPhone: 'الواتساب نفس رقم الهاتف',
    postListing: 'نشر الإعلان',
    posting: 'جاري النشر...',
    listingCreated: 'تم بنجاح!',
    listingCreatedSubtext: 'تم إنشاء إعلانك',
    noImages: 'لم تتم إضافة صور',
    noImagesMessage: 'الصور تزيد من المشاهدات والمبيعات. هل أنت متأكد من النشر بدون صور؟',
    addImages: 'إضافة صور',
    postAnyway: 'نشر على أي حال',
    noContact: 'لا توجد معلومات تواصل',
    noContactMessage: 'لن يتمكن المشترون من التواصل معك مباشرة. لا يزال بإمكانهم استخدام المحادثة داخل التطبيق. متابعة؟',
    draft: 'مسودة',
    draftFound: 'تم العثور على مسودة',
    draftFoundMessage: 'لديك مسودة غير محفوظة. هل تريد استعادتها؟',
    draftRestorePrompt: 'هل تريد استعادة المسودة المحفوظة؟',
    restoreDraft: 'استعادة المسودة',
    discardDraft: 'تجاهل',
    saveDraft: 'حفظ المسودة',
    editListing: 'تعديل الإعلان',
    updateListing: 'تحديث الإعلان',
    updating: 'جاري التحديث...',
    listingUpdated: 'تم تحديث الإعلان',
    noChanges: 'لا توجد تغييرات',
    discardChanges: 'تجاهل التغييرات؟',
    discardChangesMessage: 'لديك تغييرات غير محفوظة. هل أنت متأكد من الرجوع؟',
    // New keys for section components
    title: 'العنوان',
    titlePlaceholder: 'ماذا تبيع؟',
    change: 'تغيير',
    // Image section
    cover: 'الغلاف',
    makeCover: 'جعله غلاف',
    photoHelperText: 'الصور: {{current}}/{{max}} اختر صورة الغلاف أولاً، وأضف صوراً بزوايا وتفاصيل مختلفة.',
    takePhoto: 'التقاط صورة',
    chooseFromLibrary: 'اختيار من المعرض',
    permissionDenied: 'عذراً',
    cameraRollPermission: 'نحتاج إذن الوصول إلى معرض الصور لرفع الصور',
    cameraPermission: 'نحتاج إذن الكاميرا لالتقاط الصور',
    // Location section
    required: 'مطلوب',
    tapToSelectLocation: 'اضغط لاختيار الموقع على الخريطة',
    // Submit button
    uploadingProgress: 'جاري الرفع {{current}}/{{total}}...',
    creatingListing: 'جاري إنشاء الإعلان...',
  },
  profile: {
    profile: 'الملف الشخصي',
    editProfile: 'تعديل الملف الشخصي',
    personalDetails: 'البيانات الشخصية',
    displayName: 'الاسم المعروض',
    displayNamePlaceholder: 'أدخل اسمك',
    email: 'البريد الإلكتروني',
    emailReadOnly: 'لا يمكن تغيير البريد الإلكتروني',
    phoneNumber: 'رقم الهاتف',
    phonePlaceholder: 'أدخل رقم الهاتف',
    avatar: 'صورة الملف الشخصي',
    changePhoto: 'تغيير الصورة',
    removePhoto: 'إزالة الصورة',
    removePhotoConfirm: 'هل أنت متأكد من إزالة صورة ملفك الشخصي؟',
    saveChanges: 'حفظ التغييرات',
    unsavedChanges: 'تغييرات غير محفوظة',
    unsavedChangesMessage: 'لديك تغييرات غير محفوظة. هل أنت متأكد من الرجوع؟',
    manageAccount: 'إدارة الحساب',
    changePassword: 'تغيير كلمة المرور',
    deleteAccount: 'حذف الحساب',
    deleteAccountWarning: 'لا يمكن التراجع عن هذا الإجراء. سيتم حذف جميع بياناتك نهائياً بعد 30 يوماً.',
    deleteAccountConfirm: 'اكتب "DELETE" للتأكيد',
    typeDelete: 'DELETE',
    enterPassword: 'أدخل كلمة المرور للتأكيد',
    accountDeleted: 'تم جدولة حذف حسابك',
    oauthPasswordNote: 'قمت بتسجيل الدخول عبر {{provider}}. تغيير كلمة المرور غير متاح.',
    sellerProfile: 'ملف البائع',
    noListings: 'لا توجد إعلانات بعد',
    sellerNoListings: 'لا يوجد لدى هذا البائع إعلانات نشطة',
    listings: 'الإعلانات',
    ratings: 'التقييمات',
    ratingsComingSoon: 'التقييمات قريباً',
    joinedDate: 'انضم في {{date}}',
    daysOnPlatform: 'يوم واحد في سوق جاري',
    daysOnPlatform_plural: '{{count}} يوم في سوق جاري',
    monthsOnPlatform: 'شهر واحد في سوق جاري',
    monthsOnPlatform_plural: '{{count}} شهر في سوق جاري',
    yearsOnPlatform: 'سنة واحدة في سوق جاري',
    yearsOnPlatform_plural: '{{count}} سنة في سوق جاري',
    enterName: 'أدخل اسمك',
    enterPhone: 'أدخل رقم الهاتف',
    noEmailSet: 'لم يتم تعيين البريد الإلكتروني',
    emailSecurityNote: 'البريد الإلكتروني يُستخدم لأمان الحساب ولا يمكن تغييره',
    profileUpdated: 'تم تحديث الملف الشخصي بنجاح',
    updateFailed: 'فشل تحديث الملف الشخصي',
    memberSince: 'عضو منذ {{date}}',
    permissionRequired: 'الإذن مطلوب',
    photoLibraryPermission: 'يرجى السماح بالوصول إلى مكتبة الصور لتغيير صورة ملفك الشخصي.',
    avatarUpdateFailed: 'فشل تحديث الصورة الرمزية',
    avatarUploadFailed: 'فشل رفع الصورة الرمزية',
    uploadFailed: 'فشل الرفع',
    removePhotoFailed: 'فشل إزالة الصورة',
  },
  settings: {
    settings: 'الإعدادات',
    account: 'الحساب',
    preferences: 'التفضيلات',
    appTheme: 'مظهر التطبيق',
    themeLight: 'فاتح',
    themeDark: 'داكن',
    themeSystem: 'تلقائي',
    themeLightSubtitle: 'استخدام المظهر الفاتح دائماً',
    themeDarkSubtitle: 'استخدام المظهر الداكن دائماً',
    themeSystemSubtitle: 'مطابقة إعدادات الجهاز',
    language: 'اللغة',
    languageArabic: 'العربية',
    languageEnglish: 'English',
    notifications: 'الإشعارات',
    notificationPreferences: 'إعدادات الإشعارات',
    comingSoon: 'قريباً',
    help: 'المساعدة',
    helpCenter: 'مركز المساعدة',
    privacyPolicy: 'سياسة الخصوصية',
    termsOfUse: 'شروط الاستخدام',
    version: 'الإصدار',
    accountSettings: 'إعدادات الحساب',
    appSettings: 'إعدادات التطبيق',
    manageAccount: 'إدارة الحساب',
    manageAccountSubtitle: 'كلمة المرور والأمان والحذف',
    security: 'الأمان',
    changePassword: 'تغيير كلمة المرور',
    changePasswordSubtitle: 'تحديث كلمة المرور',
    notAvailableSocial: 'غير متاح لتسجيل الدخول الاجتماعي',
    dangerZone: 'منطقة الخطر',
    deleteAccount: 'حذف الحساب',
    deleteAccountSubtitle: 'حذف حسابك وبياناتك نهائياً',
    supportLegal: 'الدعم والقانونية',
    helpSubtitle: 'الأسئلة الشائعة والدعم',
    notificationsSubtitle: 'إدارة تفضيلات الإشعارات',
    logOut: 'تسجيل الخروج',
    logOutConfirm: 'هل أنت متأكد من تسجيل الخروج؟',
    logOutFailed: 'فشل تسجيل الخروج. يرجى المحاولة مرة أخرى.',
    signInPrompt: 'سجّل الدخول للوصول إلى إعدادات حسابك',
  },
  search: {
    search: 'بحث',
    searchPlaceholder: 'ابحث في الإعلانات...',
    recentSearches: 'عمليات البحث الأخيرة',
    clearRecent: 'مسح',
    noResults: 'لا توجد نتائج',
    noResultsFor: 'لا توجد نتائج لـ "{{query}}"',
    tryDifferent: 'جرب كلمات بحث مختلفة',
    filters: 'التصفية',
    sortBy: 'ترتيب حسب',
    sortNewest: 'الأحدث أولاً',
    sortPriceAsc: 'السعر: من الأقل للأعلى',
    sortPriceDesc: 'السعر: من الأعلى للأقل',
    priceRange: 'نطاق السعر',
    minPrice: 'الحد الأدنى',
    maxPrice: 'الحد الأقصى',
    applyFilters: 'تطبيق',
    clearFilters: 'مسح الفلاتر',
    resultsCount: '{{count}} نتيجة',
  },
  location: {
    selectLocation: 'اختر الموقع',
    currentLocation: 'موقعك الحالي',
    detectingLocation: 'جاري تحديد الموقع...',
    locationDetected: 'تم تحديد الموقع',
    locationError: 'تعذر تحديد الموقع',
    searchLocation: 'ابحث عن موقع...',
    nearYou: 'بالقرب منك',
    allSyria: 'كل سوريا',
    radius: 'النطاق',
    km: 'كم',
    confirmLocation: 'تأكيد الموقع',
    changeLocation: 'تغيير الموقع',
    myLocation: 'موقعي',
    useMyLocation: 'استخدام موقعي الحالي',
    couldNotGetLocation: 'تعذر تحديد موقعك الحالي. يرجى المحاولة مرة أخرى.',
    permissionRequired: 'الإذن مطلوب',
    pleaseAllowLocation: 'يرجى السماح بالوصول إلى الموقع لاستخدام هذه الميزة',
  },
  alerts: {
    error: 'خطأ',
    success: 'تم بنجاح',
    warning: 'تحذير',
    info: 'معلومات',
    networkError: 'خطأ في الشبكة',
    networkErrorMessage: 'يرجى التحقق من اتصالك بالإنترنت والمحاولة مرة أخرى.',
    sessionExpired: 'انتهت الجلسة',
    sessionExpiredMessage: 'يرجى تسجيل الدخول مرة أخرى.',
    permissionDenied: 'تم رفض الإذن',
    cameraPermission: 'الوصول إلى الكاميرا مطلوب لالتقاط الصور.',
    locationPermission: 'الوصول إلى الموقع مطلوب لهذه الميزة.',
    microphonePermission: 'الوصول إلى الميكروفون مطلوب لتسجيل الرسائل الصوتية.',
    storagePermission: 'الوصول إلى التخزين مطلوب لحفظ الملفات.',
  },
  errors: {
    somethingWentWrong: 'حدث خطأ ما',
    tryAgain: 'حاول مرة أخرى',
    pageNotFound: 'الصفحة غير موجودة',
    goHome: 'الذهاب للرئيسية',
    noInternet: 'لا يوجد اتصال بالإنترنت',
    serverError: 'خطأ في الخادم. يرجى المحاولة لاحقاً.',
    timeout: 'انتهت مهلة الطلب. يرجى المحاولة مرة أخرى.',
    unauthorized: 'يرجى تسجيل الدخول للمتابعة.',
    forbidden: 'ليس لديك صلاحية للوصول إلى هذا.',
    unexpected: 'حدث خطأ غير متوقع.',
  },
  time: {
    justNow: 'الآن',
    minutesAgo: 'منذ {{count}} دقيقة',
    hoursAgo: 'منذ {{count}} ساعة',
    daysAgo: 'منذ {{count}} يوم',
    weeksAgo: 'منذ {{count}} أسبوع',
    monthsAgo: 'منذ {{count}} شهر',
    yearsAgo: 'منذ {{count}} سنة',
    today: 'اليوم',
    yesterday: 'أمس',
    yesterdayAt: 'أمس {{time}}',
    overAMonthAgo: 'منذ أكثر من شهر',
    overAYearAgo: 'منذ أكثر من سنة',
    // Short format for chat list
    now: 'الآن',
    minutesShort: '{{count}}د',
    hoursShort: '{{count}}س',
    daysShort: '{{count}}ي',
  },
  validation: {
    required: 'هذا الحقل مطلوب',
    invalidEmail: 'يرجى إدخال بريد إلكتروني صحيح',
    invalidPhone: 'يرجى إدخال رقم هاتف صحيح',
    passwordTooShort: 'يجب أن تكون كلمة المرور 6 أحرف على الأقل',
    passwordsDontMatch: 'كلمتا المرور غير متطابقتين',
    priceMustBeNumber: 'يجب أن يكون السعر رقماً صحيحاً',
    titleTooShort: 'يجب أن يكون العنوان 3 أحرف على الأقل',
    titleTooLong: 'يجب أن يكون العنوان أقل من 100 حرف',
    descriptionTooLong: 'يجب أن يكون الوصف أقل من 5000 حرف',
  },
  notifications: {
    title: 'الإشعارات',
    pushNotifications: 'الإشعارات الفورية',
    enablePush: 'تفعيل الإشعارات الفورية',
    enablePushSubtitle: 'تلقي الإشعارات على جهازك',
    notificationTypes: 'أنواع الإشعارات',
    messages: 'الرسائل',
    messagesSubtitle: 'عند استلام رسالة جديدة',
    listingActivity: 'نشاط الإعلانات',
    listingActivitySubtitle: 'عند حصول إعلانك على مشاهدات أو إعجابات',
    priceDrops: 'انخفاض الأسعار',
    priceDropsSubtitle: 'عند انخفاض أسعار المفضلة',
    promoUpdates: 'العروض والتحديثات',
    promoUpdatesSubtitle: 'العروض الخاصة وتحديثات التطبيق',
    permissionNotice: 'تتطلب الإشعارات الفورية إذناً. قد تحتاج إلى تفعيلها في إعدادات جهازك إذا لم تكن قد فعلت ذلك.',
  },
  help: {
    title: 'المساعدة والدعم',
    contactSupport: 'تواصل مع الدعم',
    emailSupport: 'الدعم بالبريد الإلكتروني',
    emailSupportSubtitle: 'support@souqjari.com',
    whatsappSupport: 'دعم واتساب',
    whatsappSupportSubtitle: 'تحدث معنا مباشرة',
    whatsappComingSoon: 'دعم واتساب سيكون متاحاً قريباً. حالياً يرجى التواصل معنا عبر البريد الإلكتروني.',
    faq: 'الأسئلة الشائعة',
    responseTime: 'وقت الرد: عادة خلال 24 ساعة',
    faqPostListing: 'كيف أنشر إعلاناً؟',
    faqPostListingAnswer: 'لنشر إعلان، اضغط على زر "+" في منتصف شريط التنقل السفلي. أدخل تفاصيل المنتج بما في ذلك الصور والعنوان والوصف والسعر والفئة. ثم اضغط على "نشر" لنشر إعلانك.',
    faqEditListing: 'كيف أعدّل إعلاني؟',
    faqEditListingAnswer: 'اذهب إلى ملفك الشخصي واضغط على "إعلاناتي". ابحث عن الإعلان الذي تريد تعديله واضغط عليه. ثم اضغط على أيقونة التعديل في الزاوية العلوية لتعديل تفاصيل إعلانك.',
    faqContactSeller: 'كيف أتواصل مع البائع؟',
    faqContactSellerAnswer: 'عند عرض إعلان، يمكنك الضغط على زر "محادثة" لبدء محادثة مع البائع. يمكنك أيضاً الاتصال أو مراسلته عبر واتساب باستخدام الأزرار الموجودة أسفل صور الإعلان إذا قدم معلومات التواصل.',
    faqDeleteAccount: 'كيف أحذف حسابي؟',
    faqDeleteAccountAnswer: 'اذهب إلى الإعدادات > إدارة الحساب > حذف الحساب. ستحتاج إلى تأكيد هويتك قبل حذف الحساب. سيتم إزالة بياناتك خلال 30 يوماً.',
    faqDataSafety: 'هل بياناتي آمنة؟',
    faqDataSafetyAnswer: 'نعم، نحن نأخذ أمان البيانات بجدية. معلوماتك الشخصية مشفرة ومخزنة بأمان. لا نبيع بياناتك لأطراف ثالثة. اقرأ سياسة الخصوصية لمزيد من التفاصيل.',
    faqReportListing: 'كيف أبلغ عن إعلان؟',
    faqReportListingAnswer: 'عند عرض إعلان، اضغط على أيقونة النقاط الثلاث في الزاوية العلوية واختر "إبلاغ". اختر سبب الإبلاغ وأرسله. سيراجع فريقنا البلاغ.',
  },
  legal: {
    lastUpdated: 'آخر تحديث: {{date}}',
    // سياسة الخصوصية
    privacyPolicy: 'سياسة الخصوصية',
    privacyIntroTitle: 'مقدمة',
    privacyIntroContent: 'سوق جاري ("نحن" أو "لنا") ملتزمة بحماية خصوصيتك. توضح سياسة الخصوصية هذه كيفية جمعنا واستخدامنا ومشاركتنا لمعلوماتك الشخصية عند استخدام تطبيقنا.',
    privacyInfoCollectTitle: 'المعلومات التي نجمعها',
    privacyInfoCollectContent: '• معلومات الحساب (البريد الإلكتروني، الاسم، رقم الهاتف)\n• معلومات الملف الشخصي (الصورة الرمزية، النبذة)\n• محتوى الإعلانات (الصور، الأوصاف، الأسعار)\n• بيانات الموقع (لموقع الإعلان)\n• الرسائل بين المستخدمين\n• معلومات الجهاز وبيانات الاستخدام',
    privacyHowUseTitle: 'كيف نستخدم معلوماتك',
    privacyHowUseContent: 'نستخدم معلوماتك من أجل:\n\n• تقديم وتحسين خدماتنا\n• تمكين التواصل بين المشترين والبائعين\n• تخصيص تجربتك\n• إرسال إشعارات مهمة\n• ضمان السلامة والأمان',
    privacyDataSharingTitle: 'مشاركة البيانات',
    privacyDataSharingContent: 'قد نشارك معلوماتك مع:\n\n• المستخدمين الآخرين (الملف الشخصي والإعلانات العامة)\n• مقدمي الخدمات الذين يساعدوننا في تشغيل التطبيق\n• الجهات القانونية عند الطلب\n\nلا نبيع معلوماتك الشخصية لأطراف ثالثة.',
    privacyDataRetentionTitle: 'الاحتفاظ بالبيانات',
    privacyDataRetentionContent: 'نحتفظ ببياناتك طالما حسابك نشط. عند حذف حسابك، تتم إزالة بياناتك خلال 30 يوماً وفقاً لمتطلبات GDPR.',
    privacyYourRightsTitle: 'حقوقك',
    privacyYourRightsContent: 'لديك الحق في:\n\n• الوصول إلى بياناتك الشخصية\n• تصحيح البيانات غير الدقيقة\n• حذف حسابك وبياناتك\n• تصدير بياناتك\n• إلغاء الاشتراك في الرسائل التسويقية',
    privacySecurityTitle: 'أمان البيانات',
    privacySecurityContent: 'ننفذ إجراءات تقنية وتنظيمية مناسبة لحماية معلوماتك الشخصية من الوصول غير المصرح به أو التغيير أو الكشف أو التدمير.',
    privacyContactTitle: 'تواصل معنا',
    privacyContactContent: 'إذا كانت لديك أسئلة حول سياسة الخصوصية أو تريد ممارسة حقوقك، يرجى التواصل معنا على:\n\nprivacy@souqjari.com',
    // شروط الاستخدام
    termsOfUse: 'شروط الاستخدام',
    termsAcceptanceTitle: 'قبول الشروط',
    termsAcceptanceContent: 'باستخدام سوق جاري ("التطبيق")، فإنك توافق على الالتزام بشروط الاستخدام هذه. إذا لم توافق على هذه الشروط، يرجى عدم استخدام التطبيق.',
    termsAccountsTitle: 'حسابات المستخدمين',
    termsAccountsContent: '• يجب أن يكون عمرك 18 عاماً على الأقل لاستخدام التطبيق\n• أنت مسؤول عن الحفاظ على سرية حسابك\n• أنت مسؤول عن جميع الأنشطة تحت حسابك\n• يجب تقديم معلومات دقيقة وكاملة\n• يُسمح لكل شخص بحساب واحد فقط',
    termsListingRulesTitle: 'قواعد الإعلانات',
    termsListingRulesContent: 'عند إنشاء الإعلانات، توافق على:\n\n• إدراج المنتجات التي تملكها أو المصرح لك ببيعها فقط\n• تقديم أوصاف وصور دقيقة\n• تحديد أسعار عادلة وصادقة\n• الرد على استفسارات المشترين في الوقت المناسب\n• إتمام المعاملات بحسن نية',
    termsProhibitedTitle: 'المحتوى المحظور',
    termsProhibitedContent: 'يُحظر بشكل صارم:\n\n• المواد غير القانونية أو المسروقة\n• السلع المقلدة أو المقرصنة\n• الأسلحة والمخدرات والمواد الخطرة\n• المحتوى أو الخدمات للبالغين\n• الإعلانات الاحتيالية أو المضللة\n• الرسائل غير المرغوب فيها\n• المحتوى الذي ينتهك حقوق الملكية الفكرية',
    termsUserConductTitle: 'سلوك المستخدم',
    termsUserConductContent: 'توافق على عدم:\n\n• مضايقة أو تهديد أو إساءة معاملة المستخدمين الآخرين\n• محاولة التحايل على رسومنا أو أنظمتنا\n• استخدام التطبيق لأي غرض غير قانوني\n• التدخل في تشغيل التطبيق\n• إنشاء حسابات متعددة',
    termsIPTitle: 'الملكية الفكرية',
    termsIPContent: 'التطبيق ومحتواه الأصلي وميزاته ووظائفه مملوكة لسوق جاري ومحمية بموجب قوانين حقوق النشر والعلامات التجارية الدولية وغيرها من قوانين الملكية الفكرية.',
    termsDisclaimersTitle: 'إخلاء المسؤولية',
    termsDisclaimersContent: '• سوق جاري منصة لربط المشترين والبائعين\n• لا نتحقق من الإعلانات أو نضمن المعاملات\n• لسنا مسؤولين عن جودة المنتجات المدرجة\n• المستخدمون يتعاملون على مسؤوليتهم الخاصة\n• التطبيق مقدم "كما هو" بدون ضمانات',
    termsLiabilityTitle: 'تحديد المسؤولية',
    termsLiabilityContent: 'إلى أقصى حد يسمح به القانون، لن تكون سوق جاري مسؤولة عن أي أضرار غير مباشرة أو عرضية أو خاصة أو تبعية أو عقابية ناشئة عن استخدامك للتطبيق.',
    termsTerminationTitle: 'إنهاء الحساب',
    termsTerminationContent: 'نحتفظ بالحق في تعليق أو إنهاء الحسابات التي تنتهك هذه الشروط. يمكن للمستخدمين حذف حساباتهم في أي وقت من خلال إعدادات التطبيق.',
    termsChangesTitle: 'تغييرات على الشروط',
    termsChangesContent: 'قد نقوم بتحديث شروط الاستخدام من وقت لآخر. استمرار استخدام التطبيق بعد التغييرات يعني قبول الشروط الجديدة.',
    termsContactTitle: 'التواصل',
    termsContactContent: 'للأسئلة حول شروط الاستخدام، يرجى التواصل على:\n\nlegal@souqjari.com',
  },
  manageAccount: {
    title: 'إدارة الحساب',
    deleteAccountTitle: 'حذف الحساب',
    deleteAccountWarning: 'هل أنت متأكد من حذف حسابك؟ لا يمكن التراجع عن هذا الإجراء. سيتم حذف جميع إعلاناتك ورسائلك وبياناتك نهائياً.',
    deleteAccountPermanent: 'هذا الإجراء نهائي',
    deleteAccountPermanentMessage: 'بمجرد حذف حسابك، ستتم إزالة جميع بياناتك بما في ذلك الإعلانات والرسائل ومعلومات الملف الشخصي نهائياً ولا يمكن استعادتها.',
    typeDeleteToConfirm: 'اكتب DELETE للتأكيد',
    typeDeleteExact: 'يرجى كتابة DELETE بالضبط كما هو موضح',
    enterPasswordToConfirm: 'أدخل كلمة المرور للتأكيد',
    enterPassword: 'أدخل كلمة المرور',
    deleteMyAccount: 'حذف حسابي',
    oauthDeleteMessage: 'قمت بتسجيل الدخول عبر {{provider}}. اكتب DELETE لتأكيد حذف الحساب.',
    passwordIncorrect: 'كلمة المرور غير صحيحة.',
    deleteError: 'فشل حذف الحساب. يرجى المحاولة مرة أخرى.',
  },
};

export default ar;
