// Arabic translations (primary language)
import { TranslationResources } from './types';

const ar: TranslationResources = {
  common: {
    loading: 'جاري التحميل...',
    error: 'خطأ',
    retry: 'حاول مجدداً',
    cancel: 'إلغاء',
    save: 'حفظ',
    delete: 'حذف',
    edit: 'تعديل',
    search: 'بحث',
    noResults: 'لا توجد نتائج',
    signIn: 'تسجيل الدخول',
    signUp: 'إنشاء حساب',
    signInRequired: 'تسجيل الدخول مطلوب',
    comingSoon: 'قريباً',
    ok: 'حسناً',
    yes: 'نعم',
    no: 'لا',
    confirm: 'تأكيد',
    close: 'إغلاق',
    back: 'رجوع',
    next: 'التالي',
    done: 'تم',
    submit: 'إرسال',
    continue: 'متابعة',
    viewAll: 'عرض الكل',
    seeAll: 'مشاهدة الكل',
    share: 'مشاركة',
    report: 'إبلاغ',
    block: 'حظر',
    unblock: 'إلغاء الحظر',
    moreOptions: 'المزيد من الخيارات',
    selectOption: 'اختر خياراً',
    required: 'مطلوب',
    optional: 'اختياري',
    item: 'عنصر',
    items: 'عناصر',
  },

  auth: {
    loginOrSignup: 'تسجيل الدخول أو إنشاء حساب',
    emailAddress: 'البريد الإلكتروني',
    enterEmail: 'أدخل بريدك الإلكتروني',
    invalidEmail: 'يرجى إدخال بريد إلكتروني صحيح',
    password: 'كلمة المرور',
    enterPassword: 'أدخل كلمة المرور',
    createPassword: 'أنشئ كلمة مرور',
    forgotPassword: 'نسيت كلمة المرور؟',
    forgotPasswordTitle: 'نسيت كلمة المرور؟',
    forgotPasswordSubtitle: 'أدخل بريدك الإلكتروني وسنرسل لك رمز التحقق.',
    sendCode: 'إرسال الرمز',
    resetPassword: 'إعادة تعيين كلمة المرور',
    newPassword: 'كلمة المرور الجديدة',
    newPasswordSubtitle: 'أنشئ كلمة مرور قوية لحسابك.',
    createAccount: 'إنشاء حساب',
    welcomeBack: 'أهلاً بعودتك',
    setUpAccount: 'أعد حسابك للبدء',
    enterPasswordToSignIn: 'أدخل كلمة المرور لتسجيل الدخول',
    yourName: 'اسمك',
    enterFullName: 'أدخل اسمك الكامل',
    termsFooter: 'بالمتابعة، أنت توافق على',
    termsOfService: 'شروط الخدمة',
    privacyPolicy: 'سياسة الخصوصية',
    and: 'و',
    verifyEmail: 'تحقق من بريدك الإلكتروني',
    verificationCodeSent: 'تم إرسال رمز تحقق مكون من 6 أرقام إلى',
    enterCode: 'أدخل الرمز',
    verifyCode: 'تحقق من الرمز',
    resendCode: 'إعادة إرسال الرمز',
    didntReceiveCode: 'لم تستلم الرمز؟ أعد الإرسال',
    backToSignIn: 'العودة لتسجيل الدخول',
    emailVerified: 'تم التحقق من البريد الإلكتروني!',
    emailVerifiedSubtitle: 'تم التحقق من بريدك الإلكتروني بنجاح. يمكنك الآن البدء باستخدام سوق جاري.',
    getStarted: 'ابدأ الآن',
    passwordReset: 'تم إعادة تعيين كلمة المرور!',
    passwordResetSubtitle: 'تم إعادة تعيين كلمة المرور بنجاح. يمكنك الآن تسجيل الدخول بكلمة المرور الجديدة.',
    signInMethod: 'طريقة تسجيل الدخول',
    oauthOnlyMessage: 'تم إنشاء هذا الحساب باستخدام {{provider}}. يرجى استخدام زر "{{provider}}" أدناه لتسجيل الدخول.',
    accountNotFound: 'الحساب غير موجود',
    accountNotFoundMessage: 'لا يوجد حساب مسجل بهذا البريد الإلكتروني.',
    invalidCode: 'رمز غير صحيح',
    invalidCodeMessage: 'الرمز الذي أدخلته غير صحيح أو منتهي الصلاحية. يرجى المحاولة مجدداً.',
    codeSent: 'تم إرسال الرمز',
    codeSentMessage: 'تم إرسال رمز تحقق جديد إلى بريدك الإلكتروني.',
    passwordMinLength: 'يجب أن تكون كلمة المرور 6 أحرف على الأقل',
    enterName: 'يرجى إدخال اسمك',
    change: 'تغيير',
  },

  tabs: {
    home: 'الرئيسية',
    chats: 'المحادثات',
    post: 'نشر',
    favorites: 'المفضلة',
    myListings: 'إعلاناتي',
  },

  home: {
    searchPlaceholder: 'ابحث في جميع الإعلانات...',
    allCategories: 'جميع الفئات',
    recentlyViewed: 'شوهدت مؤخراً',
    clearAll: 'مسح الكل',
    noRecentlyViewed: 'لا توجد إعلانات شوهدت مؤخراً',
  },

  listing: {
    price: 'السعر',
    description: 'الوصف',
    location: 'الموقع',
    openInMaps: 'فتح في الخرائط',
    contactSeller: 'تواصل مع البائع',
    chat: 'محادثة',
    call: 'اتصال',
    whatsapp: 'واتساب',
    sold: 'مُباع',
    unavailable: 'غير متوفر',
    listingNotFound: 'الإعلان غير موجود',
    goBack: 'العودة',
    signInToChat: 'يرجى تسجيل الدخول للمحادثة مع البائع',
    cantChatOwnListing: 'لا يمكنك المحادثة على إعلانك الخاص',
    failedToStartConversation: 'فشل في بدء المحادثة',
    failedToLoad: 'فشل في تحميل الإعلان',
    listedBy: 'معروض بواسطة',
    activeListings: 'إعلانات نشطة',
    moreFromSeller: 'المزيد من هذا البائع',
    viewSellerProfile: 'عرض الملف الشخصي',
    shareListingMessage: 'شاهد هذا الإعلان: {{title}}',
  },

  createListing: {
    createListing: 'إنشاء إعلان',
    editListing: 'تعديل الإعلان',
    title: 'العنوان',
    titlePlaceholder: 'ماذا تبيع؟',
    descriptionPlaceholder: 'صف منتجك بالتفصيل...',
    pricePlaceholder: 'أدخل السعر',
    category: 'الفئة',
    subcategory: 'الفئة الفرعية',
    selectCategory: 'اختر فئة',
    selectSubcategory: 'اختر فئة فرعية',
    addPhotos: 'أضف صور',
    addMorePhotos: 'أضف المزيد من الصور',
    photoLimit: '{{current}}/{{max}} صور',
    setLocation: 'تحديد الموقع',
    changeLocation: 'تغيير الموقع',
    contactInfo: 'معلومات الاتصال',
    phoneNumber: 'رقم الهاتف',
    whatsappNumber: 'رقم الواتساب',
    sameAsPhone: 'نفس رقم الهاتف',
    publish: 'نشر الإعلان',
    saveChanges: 'حفظ التغييرات',
    saveDraft: 'حفظ كمسودة',
    discardChanges: 'تجاهل التغييرات',
    requiredField: 'هذا الحقل مطلوب',
    listingCreated: 'تم إنشاء الإعلان بنجاح!',
    listingUpdated: 'تم تحديث الإعلان بنجاح!',
    listingDeleted: 'تم حذف الإعلان بنجاح!',
  },

  myListings: {
    noListingsYet: 'لا توجد إعلانات بعد',
    startSelling: 'ابدأ البيع بنشر إعلانك الأول',
    createFirstListing: 'أنشئ إعلانك الأول',
    all: 'الكل',
    active: 'نشط',
    soldStatus: 'مُباع',
    hidden: 'مخفي',
    noActiveListings: 'لا توجد لديك إعلانات نشطة',
    noSoldItems: 'لم تبع أي منتجات بعد',
    noHiddenListings: 'لا توجد لديك إعلانات مخفية',
    markAsSold: 'تحديد كمُباع',
    markAsActive: 'تحديد كنشط',
    hide: 'إخفاء',
    unhide: 'إظهار',
    deleteListing: 'حذف الإعلان',
    deleteConfirmTitle: 'حذف الإعلان',
    deleteConfirmMessage: 'هل أنت متأكد أنك تريد حذف هذا الإعلان؟ لا يمكن التراجع عن هذا الإجراء.',
    restoreListing: 'استعادة الإعلان',
  },

  favorites: {
    noFavoritesYet: 'لا توجد مفضلات بعد',
    savedListingsAppear: 'الإعلانات التي تحفظها ستظهر هنا',
    browseListings: 'تصفح الإعلانات',
    signInToViewFavorites: 'يرجى تسجيل الدخول لحفظ ومشاهدة المفضلة',
  },

  chats: {
    messages: 'الرسائل',
    noConversationsYet: 'لا توجد محادثات بعد',
    startChatting: 'ابدأ المحادثة مع البائعين بزيارة إعلان والضغط على "محادثة"',
    browseListingsToChat: 'تصفح الإعلانات',
    signInToViewMessages: 'يرجى تسجيل الدخول لعرض رسائلك',
    deleteConversation: 'حذف المحادثة',
    deleteConversationConfirm: 'هل أنت متأكد أنك تريد حذف هذه المحادثة؟',
    deleteConversations: 'حذف المحادثات',
    deleteConversationsConfirm: 'هل أنت متأكد أنك تريد حذف {{count}} محادثات؟',
    typeMessage: 'اكتب رسالة...',
    send: 'إرسال',
    voiceMessage: 'رسالة صوتية',
    startConversation: 'ابدأ محادثة...',
    now: 'الآن',
    user: 'مستخدم',
    listing: 'إعلان',
  },

  user: {
    account: 'الحساب',
    signInToAccess: 'سجل الدخول للوصول إلى إعدادات حسابك',
    dontHaveAccount: 'ليس لديك حساب؟ أنشئ حساب',
    memberSince: 'عضو منذ',
    accountSettings: 'إعدادات الحساب',
    manageAccount: 'إدارة الحساب',
    passwordDeleteAccount: 'كلمة المرور، حذف الحساب',
    appSettings: 'إعدادات التطبيق',
    appTheme: 'مظهر التطبيق',
    notificationPreferences: 'تفضيلات الإشعارات',
    pushNotificationsEmail: 'الإشعارات الفورية، تنبيهات البريد',
    supportLegal: 'الدعم والقانون',
    help: 'المساعدة',
    faqsSupport: 'الأسئلة الشائعة والدعم',
    logOut: 'تسجيل الخروج',
    logOutConfirm: 'هل أنت متأكد أنك تريد تسجيل الخروج؟',
    failedToLogOut: 'فشل تسجيل الخروج. يرجى المحاولة مجدداً.',
    themeLight: 'فاتح',
    themeDark: 'داكن',
    themeSystem: 'إعدادات النظام',
  },

  personalDetails: {
    personalDetails: 'البيانات الشخصية',
    profilePhoto: 'صورة الملف الشخصي',
    changePhoto: 'تغيير الصورة',
    displayName: 'الاسم المعروض',
    email: 'البريد الإلكتروني',
    phone: 'رقم الهاتف',
    saveProfile: 'حفظ الملف الشخصي',
    profileUpdated: 'تم تحديث الملف الشخصي بنجاح!',
    profileUpdateFailed: 'فشل تحديث الملف الشخصي. يرجى المحاولة مجدداً.',
  },

  manageAccount: {
    changePassword: 'تغيير كلمة المرور',
    currentPassword: 'كلمة المرور الحالية',
    newPasswordField: 'كلمة المرور الجديدة',
    confirmPassword: 'تأكيد كلمة المرور',
    passwordsDontMatch: 'كلمات المرور غير متطابقة',
    passwordChanged: 'تم تغيير كلمة المرور بنجاح!',
    deleteAccount: 'حذف الحساب',
    deleteAccountWarning: 'هذا الإجراء دائم ولا يمكن التراجع عنه. سيتم حذف جميع بياناتك.',
    deleteAccountConfirm: 'هل أنت متأكد أنك تريد حذف حسابك؟',
    typeDeleteToConfirm: 'اكتب "DELETE" للتأكيد',
    accountDeleted: 'تم حذف الحساب بنجاح',
  },

  search: {
    searchListings: 'ابحث في الإعلانات...',
    recentSearches: 'عمليات البحث الأخيرة',
    clearRecentSearches: 'مسح عمليات البحث الأخيرة',
    noResultsFor: 'لا توجد نتائج لـ "{{query}}"',
    tryDifferentKeywords: 'جرب كلمات مختلفة أو تصفح الفئات',
    filterResults: 'تصفية النتائج',
    sortBy: 'ترتيب حسب',
    priceRange: 'نطاق السعر',
    minPrice: 'الحد الأدنى',
    maxPrice: 'الحد الأقصى',
    applyFilters: 'تطبيق الفلاتر',
    clearFilters: 'مسح الفلاتر',
    resultsFound: 'تم العثور على {{count}} نتيجة',
  },

  location: {
    selectLocation: 'اختر الموقع',
    currentLocation: 'الموقع الحالي',
    useCurrentLocation: 'استخدم الموقع الحالي',
    searchLocation: 'ابحث عن موقع...',
    locationPermission: 'إذن الموقع',
    locationPermissionMessage: 'نحتاج موقعك لعرض الإعلانات القريبة',
    enableLocation: 'تفعيل الموقع',
    radius: 'النطاق',
    km: 'كم',
    allLocations: 'جميع المواقع',
    syria: 'سوريا',
    nearby: 'قريب',
  },

  categories: {
    buyAndSell: 'بيع وشراء',
    cars: 'سيارات',
    realEstate: 'عقارات',
    jobs: 'وظائف',
    services: 'خدمات',
    pets: 'حيوانات',
    electronics: 'إلكترونيات',
    furniture: 'أثاث',
    clothing: 'ملابس',
    books: 'كتب',
    phones: 'هواتف',
    computers: 'كمبيوترات',
    homeAppliances: 'أجهزة منزلية',
    toysAndGames: 'ألعاب',
    sportsEquipment: 'معدات رياضية',
    other: 'أخرى',
    carsAndTrucks: 'سيارات وشاحنات',
    motorcycles: 'دراجات نارية',
    vehicleParts: 'قطع غيار',
    forRent: 'للإيجار',
    forSale: 'للبيع',
    accounting: 'محاسبة',
    customerService: 'خدمة عملاء',
    healthcare: 'رعاية صحية',
    sales: 'مبيعات',
    itAndProgramming: 'تكنولوجيا وبرمجة',
    homeMaintenance: 'صيانة منزلية',
    tutoring: 'دروس خصوصية',
    cleaning: 'تنظيف',
    moving: 'نقل',
    cats: 'قطط',
    dogs: 'كلاب',
    birds: 'طيور',
  },

  errors: {
    somethingWentWrong: 'حدث خطأ ما',
    tryAgain: 'يرجى المحاولة مجدداً',
    networkError: 'خطأ في الشبكة',
    checkConnection: 'يرجى التحقق من اتصالك بالإنترنت',
    sessionExpired: 'انتهت الجلسة',
    pleaseSignInAgain: 'يرجى تسجيل الدخول مجدداً',
    permissionDenied: 'تم رفض الإذن',
    invalidInput: 'إدخال غير صالح',
    unableToMakeCall: 'تعذر إجراء المكالمة',
    whatsappNotInstalled: 'واتساب غير مثبت',
    failedToShare: 'فشل في المشاركة',
  },

  time: {
    justNow: 'الآن',
    minuteAgo: 'منذ دقيقة',
    minutesAgo: 'منذ {{count}} دقائق',
    hourAgo: 'منذ ساعة',
    hoursAgo: 'منذ {{count}} ساعات',
    dayAgo: 'منذ يوم',
    daysAgo: 'منذ {{count}} أيام',
    weekAgo: 'منذ أسبوع',
    weeksAgo: 'منذ {{count}} أسابيع',
    monthAgo: 'منذ شهر',
    monthsAgo: 'منذ {{count}} أشهر',
    yearAgo: 'منذ سنة',
    yearsAgo: 'منذ {{count}} سنوات',
  },
};

export default ar;
