import { TranslationKeys } from './types';

const ar: TranslationKeys = {
  common: {
    loading: 'جاري التحميل...',
    error: 'حدث خطأ',
    retry: 'إعادة المحاولة',
    cancel: 'إلغاء',
    save: 'حفظ',
    delete: 'حذف',
    edit: 'تعديل',
    search: 'بحث',
    noResults: 'لا توجد نتائج',
    confirm: 'تأكيد',
    yes: 'نعم',
    no: 'لا',
    ok: 'حسناً',
    done: 'تم',
    next: 'التالي',
    back: 'رجوع',
    close: 'إغلاق',
    share: 'مشاركة',
    refresh: 'تحديث',
    seeAll: 'عرض الكل',
    showMore: 'عرض المزيد',
    showLess: 'عرض أقل',
  },
  auth: {
    loginOrSignup: 'تسجيل الدخول أو إنشاء حساب',
    emailPlaceholder: 'أدخل بريدك الإلكتروني',
    emailLabel: 'البريد الإلكتروني',
    passwordPlaceholder: 'أدخل كلمة المرور',
    passwordLabel: 'كلمة المرور',
    namePlaceholder: 'أدخل اسمك الكامل',
    nameLabel: 'الاسم',
    continue: 'متابعة',
    createAccount: 'إنشاء حساب',
    welcomeBack: 'مرحباً بعودتك',
    signIn: 'تسجيل الدخول',
    signOut: 'تسجيل الخروج',
    signOutConfirmTitle: 'تسجيل الخروج',
    signOutConfirmMessage: 'هل أنت متأكد من تسجيل الخروج؟',
    forgotPassword: 'نسيت كلمة المرور؟',
    orContinueWith: 'أو المتابعة عبر',
    verifyEmail: 'تأكيد البريد الإلكتروني',
    verifyEmailSubtitle: 'أرسلنا رمز تحقق مكون من 6 أرقام إلى',
    enterCode: 'أدخل الرمز',
    resendCode: 'إعادة إرسال الرمز',
    codeSent: 'تم إرسال رمز تحقق جديد إلى بريدك الإلكتروني.',
    codeExpired: 'انتهت صلاحية رمز التحقق. يرجى طلب رمز جديد.',
    invalidCode: 'رمز التحقق الذي أدخلته غير صحيح.',
    emailVerified: 'تم تأكيد البريد الإلكتروني!',
    emailVerifiedSubtitle: 'تم تأكيد بريدك الإلكتروني بنجاح. يمكنك الآن البدء في استخدام سوق جاري.',
    getStarted: 'ابدأ الآن',
    passwordReset: 'تم إعادة تعيين كلمة المرور!',
    passwordResetSubtitle: 'تم إعادة تعيين كلمة المرور بنجاح. يمكنك الآن تسجيل الدخول بكلمة المرور الجديدة.',
    newPassword: 'كلمة المرور الجديدة',
    newPasswordPlaceholder: 'أنشئ كلمة مرور جديدة',
    setNewPassword: 'تعيين كلمة المرور الجديدة',
    passwordRequirements: {
      title: 'يجب أن تحتوي كلمة المرور على:',
      minLength: '6 أحرف على الأقل',
      uppercase: 'حرف كبير واحد',
      lowercase: 'حرف صغير واحد',
      number: 'رقم واحد',
    },
    oauthError: 'حدثت مشكلة في تسجيل الدخول. يرجى المحاولة مرة أخرى.',
    signInMethod: 'طريقة تسجيل الدخول',
    signInMethodMessage: 'تم إنشاء هذا الحساب باستخدام {{provider}}. يرجى استخدام زر {{provider}} لتسجيل الدخول.',
  },
  tabs: {
    home: 'الرئيسية',
    chats: 'المحادثات',
    post: 'إعلان جديد',
    favorites: 'المفضلة',
    myListings: 'إعلاناتي',
  },
  home: {
    greeting: 'مرحباً بك في سوق جاري',
    searchPlaceholder: 'ابحث في الإعلانات...',
    categories: 'الفئات',
    recentlyViewed: 'شوهد مؤخراً',
    noRecentlyViewed: 'لم تشاهد أي إعلانات بعد',
    browseListings: 'تصفح الإعلانات',
  },
  listings: {
    myListings: 'إعلاناتي',
    noListings: 'لا توجد إعلانات',
    noListingsSubtext: 'ابدأ البيع بإنشاء إعلانك الأول',
    createFirst: 'أنشئ إعلانك الأول',
    createListing: 'إنشاء إعلان',
    active: 'نشط',
    sold: 'مباع',
    inactive: 'غير نشط',
    deleted: 'محذوف',
    all: 'الكل',
    markAsSold: 'تحديد كمباع',
    markAsActive: 'تحديد كنشط',
    deactivate: 'إلغاء التفعيل',
    restore: 'استعادة',
    deletePermanently: 'حذف نهائي',
    deleteConfirmTitle: 'إزالة الإعلان',
    deleteConfirmMessage: 'سيتم إخفاء الإعلان عن المشترين. يمكنك استعادته لاحقاً.',
    permanentDeleteConfirmTitle: 'حذف نهائي؟',
    permanentDeleteConfirmMessage: 'لا يمكن التراجع عن هذا الإجراء. سيتم حذف الإعلان نهائياً.',
    statusUpdated: 'تم تحديث حالة الإعلان',
    listingDeleted: 'تم حذف الإعلان',
    listingRestored: 'تم استعادة الإعلان',
    viewListing: 'عرض الإعلان',
    editListing: 'تعديل الإعلان',
    postedBy: 'نشر بواسطة',
    memberSince: 'عضو منذ',
    viewProfile: 'عرض الملف الشخصي',
    contactSeller: 'التواصل مع البائع',
    startChat: 'بدء محادثة',
    callSeller: 'اتصال',
    whatsappSeller: 'واتساب',
    price: 'السعر',
    free: 'مجاني',
    negotiable: 'قابل للتفاوض',
    location: 'الموقع',
    description: 'الوصف',
    noDescription: 'لا يوجد وصف',
    category: 'الفئة',
    posted: 'نُشر',
    updated: 'تم التحديث',
    views: 'مشاهدات',
    favorites: 'مفضلة',
    shareError: 'تعذر مشاركة الإعلان',
  },
  chat: {
    messages: 'الرسائل',
    noConversations: 'لا توجد محادثات',
    noConversationsSubtext: 'ابدأ المحادثة مع البائعين بزيارة إعلان والضغط على "محادثة"',
    startChatting: 'ابدأ المحادثة',
    browseListings: 'تصفح الإعلانات',
    typeMessage: 'اكتب رسالة...',
    send: 'إرسال',
    sending: 'جاري الإرسال...',
    sent: 'تم الإرسال',
    delivered: 'تم التوصيل',
    read: 'مقروءة',
    voiceMessage: 'رسالة صوتية',
    holdToRecord: 'اضغط مطولاً للتسجيل',
    releaseToSend: 'أفلت للإرسال',
    recording: 'جاري التسجيل...',
    tapToPlay: 'اضغط للتشغيل',
    today: 'اليوم',
    yesterday: 'أمس',
    online: 'متصل',
    offline: 'غير متصل',
    typing: 'يكتب...',
    selectConversations: 'تحديد',
    deleteConversations: 'حذف',
    deleteConversationsConfirm: 'حذف {{count}} محادثة؟',
    signInRequired: 'تسجيل الدخول مطلوب',
    signInRequiredSubtext: 'يرجى تسجيل الدخول لعرض رسائلك',
    listingDeleted: 'تم حذف هذا الإعلان',
    listingUnavailable: 'الإعلان غير متوفر',
  },
  favorites: {
    favorites: 'المفضلة',
    noFavorites: 'لا توجد مفضلات',
    noFavoritesSubtext: 'احفظ الإعلانات التي تعجبك بالضغط على أيقونة القلب',
    browseNow: 'تصفح الآن',
    removeFavorite: 'إزالة من المفضلة',
    addFavorite: 'إضافة إلى المفضلة',
    signInRequired: 'تسجيل الدخول مطلوب',
    signInRequiredSubtext: 'يرجى تسجيل الدخول لعرض مفضلاتك',
  },
  post: {
    postListing: 'نشر إعلان',
    titlePlaceholder: 'العنوان...',
    titleLabel: 'عنوان الإعلان',
    selectCategory: 'اختر فئة',
    categorySelected: '{{subcategory}} ‹ {{category}}',
    continue: 'متابعة',
    missingTitle: 'يرجى إدخال عنوان لإعلانك',
    missingCategory: 'يرجى اختيار فئة',
  },
  productDetails: {
    listingDetails: 'تفاصيل الإعلان',
    description: 'الوصف',
    descriptionPlaceholder: 'صف المنتج بدقة...',
    price: 'السعر',
    pricePlaceholder: 'أدخل السعر',
    currency: 'العملة',
    location: 'الموقع',
    locationPlaceholder: 'اختر الموقع',
    selectLocation: 'اختر الموقع',
    photos: 'الصور',
    addPhotos: 'إضافة صور',
    photoLimit: '{{max}}/{{current}} صور',
    removePhoto: 'إزالة',
    contactInfo: 'معلومات التواصل',
    phoneNumber: 'رقم الهاتف',
    phonePlaceholder: 'أدخل رقم الهاتف',
    whatsappNumber: 'رقم الواتساب',
    whatsappPlaceholder: 'أدخل رقم الواتساب',
    sameAsPhone: 'الواتساب نفس رقم الهاتف',
    postListing: 'نشر الإعلان',
    posting: 'جاري النشر...',
    listingCreated: 'تم بنجاح!',
    listingCreatedSubtext: 'تم إنشاء إعلانك',
    noImages: 'لم تتم إضافة صور',
    noImagesMessage: 'الصور تزيد من المشاهدات والمبيعات. هل أنت متأكد من النشر بدون صور؟',
    addImages: 'إضافة صور',
    postAnyway: 'نشر على أي حال',
    noContact: 'لا توجد معلومات تواصل',
    noContactMessage: 'لن يتمكن المشترون من التواصل معك مباشرة. لا يزال بإمكانهم استخدام المحادثة داخل التطبيق. متابعة؟',
    draft: 'مسودة',
    draftFound: 'تم العثور على مسودة',
    draftFoundMessage: 'لديك مسودة غير محفوظة. هل تريد استعادتها؟',
    restoreDraft: 'استعادة المسودة',
    discardDraft: 'تجاهل',
    saveDraft: 'حفظ المسودة',
    editListing: 'تعديل الإعلان',
    updateListing: 'تحديث الإعلان',
    updating: 'جاري التحديث...',
    listingUpdated: 'تم تحديث الإعلان',
    noChanges: 'لا توجد تغييرات',
    discardChanges: 'تجاهل التغييرات؟',
    discardChangesMessage: 'لديك تغييرات غير محفوظة. هل أنت متأكد من الرجوع؟',
  },
  profile: {
    profile: 'الملف الشخصي',
    editProfile: 'تعديل الملف الشخصي',
    personalDetails: 'البيانات الشخصية',
    displayName: 'الاسم المعروض',
    displayNamePlaceholder: 'أدخل اسمك',
    email: 'البريد الإلكتروني',
    emailReadOnly: 'لا يمكن تغيير البريد الإلكتروني',
    phoneNumber: 'رقم الهاتف',
    phonePlaceholder: 'أدخل رقم الهاتف',
    avatar: 'صورة الملف الشخصي',
    changePhoto: 'تغيير الصورة',
    removePhoto: 'إزالة الصورة',
    removePhotoConfirm: 'هل أنت متأكد من إزالة صورة ملفك الشخصي؟',
    saveChanges: 'حفظ التغييرات',
    unsavedChanges: 'تغييرات غير محفوظة',
    unsavedChangesMessage: 'لديك تغييرات غير محفوظة. هل أنت متأكد من الرجوع؟',
    manageAccount: 'إدارة الحساب',
    changePassword: 'تغيير كلمة المرور',
    deleteAccount: 'حذف الحساب',
    deleteAccountWarning: 'لا يمكن التراجع عن هذا الإجراء. سيتم حذف جميع بياناتك نهائياً بعد 30 يوماً.',
    deleteAccountConfirm: 'اكتب "DELETE" للتأكيد',
    typeDelete: 'DELETE',
    enterPassword: 'أدخل كلمة المرور للتأكيد',
    accountDeleted: 'تم جدولة حذف حسابك',
    oauthPasswordNote: 'قمت بتسجيل الدخول عبر {{provider}}. تغيير كلمة المرور غير متاح.',
    sellerProfile: 'ملف البائع',
    noListings: 'لا توجد إعلانات بعد',
    sellerNoListings: 'لا يوجد لدى هذا البائع إعلانات نشطة',
    listings: 'الإعلانات',
    ratings: 'التقييمات',
    ratingsComingSoon: 'التقييمات قريباً',
    joinedDate: 'انضم في {{date}}',
    daysOnPlatform: 'يوم واحد في سوق جاري',
    daysOnPlatform_plural: '{{count}} يوم في سوق جاري',
    monthsOnPlatform: 'شهر واحد في سوق جاري',
    monthsOnPlatform_plural: '{{count}} شهر في سوق جاري',
    yearsOnPlatform: 'سنة واحدة في سوق جاري',
    yearsOnPlatform_plural: '{{count}} سنة في سوق جاري',
  },
  settings: {
    settings: 'الإعدادات',
    account: 'الحساب',
    preferences: 'التفضيلات',
    appTheme: 'مظهر التطبيق',
    themeLight: 'فاتح',
    themeDark: 'داكن',
    themeSystem: 'تلقائي',
    language: 'اللغة',
    languageArabic: 'العربية',
    languageEnglish: 'English',
    notifications: 'الإشعارات',
    notificationPreferences: 'إعدادات الإشعارات',
    comingSoon: 'قريباً',
    help: 'المساعدة',
    helpCenter: 'مركز المساعدة',
    privacyPolicy: 'سياسة الخصوصية',
    termsOfUse: 'شروط الاستخدام',
    version: 'الإصدار',
  },
  search: {
    search: 'بحث',
    searchPlaceholder: 'ابحث في الإعلانات...',
    recentSearches: 'عمليات البحث الأخيرة',
    clearRecent: 'مسح',
    noResults: 'لا توجد نتائج',
    noResultsFor: 'لا توجد نتائج لـ "{{query}}"',
    tryDifferent: 'جرب كلمات بحث مختلفة',
    filters: 'التصفية',
    sortBy: 'ترتيب حسب',
    sortNewest: 'الأحدث أولاً',
    sortPriceAsc: 'السعر: من الأقل للأعلى',
    sortPriceDesc: 'السعر: من الأعلى للأقل',
    priceRange: 'نطاق السعر',
    minPrice: 'الحد الأدنى',
    maxPrice: 'الحد الأقصى',
    applyFilters: 'تطبيق',
    clearFilters: 'مسح الفلاتر',
    resultsCount: '{{count}} نتيجة',
  },
  location: {
    selectLocation: 'اختر الموقع',
    currentLocation: 'موقعك الحالي',
    detectingLocation: 'جاري تحديد الموقع...',
    locationDetected: 'تم تحديد الموقع',
    locationError: 'تعذر تحديد الموقع',
    searchLocation: 'ابحث عن موقع...',
    nearYou: 'بالقرب منك',
    allSyria: 'كل سوريا',
    radius: 'النطاق',
    km: 'كم',
    confirmLocation: 'تأكيد الموقع',
    changeLocation: 'تغيير الموقع',
  },
  alerts: {
    error: 'خطأ',
    success: 'تم بنجاح',
    warning: 'تحذير',
    info: 'معلومات',
    networkError: 'خطأ في الشبكة',
    networkErrorMessage: 'يرجى التحقق من اتصالك بالإنترنت والمحاولة مرة أخرى.',
    sessionExpired: 'انتهت الجلسة',
    sessionExpiredMessage: 'يرجى تسجيل الدخول مرة أخرى.',
    permissionDenied: 'تم رفض الإذن',
    cameraPermission: 'الوصول إلى الكاميرا مطلوب لالتقاط الصور.',
    locationPermission: 'الوصول إلى الموقع مطلوب لهذه الميزة.',
    microphonePermission: 'الوصول إلى الميكروفون مطلوب لتسجيل الرسائل الصوتية.',
    storagePermission: 'الوصول إلى التخزين مطلوب لحفظ الملفات.',
  },
  errors: {
    somethingWentWrong: 'حدث خطأ ما',
    tryAgain: 'حاول مرة أخرى',
    pageNotFound: 'الصفحة غير موجودة',
    goHome: 'الذهاب للرئيسية',
    noInternet: 'لا يوجد اتصال بالإنترنت',
    serverError: 'خطأ في الخادم. يرجى المحاولة لاحقاً.',
    timeout: 'انتهت مهلة الطلب. يرجى المحاولة مرة أخرى.',
    unauthorized: 'يرجى تسجيل الدخول للمتابعة.',
    forbidden: 'ليس لديك صلاحية للوصول إلى هذا.',
  },
  time: {
    justNow: 'الآن',
    minutesAgo: 'منذ {{count}} دقيقة',
    hoursAgo: 'منذ {{count}} ساعة',
    daysAgo: 'منذ {{count}} يوم',
    weeksAgo: 'منذ {{count}} أسبوع',
    monthsAgo: 'منذ {{count}} شهر',
    yearsAgo: 'منذ {{count}} سنة',
    today: 'اليوم',
    yesterday: 'أمس',
    yesterdayAt: 'أمس {{time}}',
    overAMonthAgo: 'منذ أكثر من شهر',
    overAYearAgo: 'منذ أكثر من سنة',
  },
  validation: {
    required: 'هذا الحقل مطلوب',
    invalidEmail: 'يرجى إدخال بريد إلكتروني صحيح',
    invalidPhone: 'يرجى إدخال رقم هاتف صحيح',
    passwordTooShort: 'يجب أن تكون كلمة المرور 6 أحرف على الأقل',
    passwordsDontMatch: 'كلمتا المرور غير متطابقتين',
    priceMustBeNumber: 'يجب أن يكون السعر رقماً صحيحاً',
    titleTooShort: 'يجب أن يكون العنوان 3 أحرف على الأقل',
    titleTooLong: 'يجب أن يكون العنوان أقل من 100 حرف',
    descriptionTooLong: 'يجب أن يكون الوصف أقل من 5000 حرف',
  },
};

export default ar;
