import { TranslationKeys } from './types';

const en: TranslationKeys = {
  common: {
    loading: 'Loading...',
    error: 'An error occurred',
    retry: 'Retry',
    cancel: 'Cancel',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    search: 'Search',
    noResults: 'No results found',
    confirm: 'Confirm',
    yes: 'Yes',
    no: 'No',
    ok: 'OK',
    done: 'Done',
    next: 'Next',
    back: 'Back',
    close: 'Close',
    share: 'Share',
    refresh: 'Refresh',
    seeAll: 'See All',
    showMore: 'Show More',
    showLess: 'Show Less',
  },
  auth: {
    loginOrSignup: 'Log in or Sign up',
    emailPlaceholder: 'Enter your email address',
    emailLabel: 'Email Address',
    passwordPlaceholder: 'Enter your password',
    passwordLabel: 'Password',
    namePlaceholder: 'Enter your full name',
    nameLabel: 'Your Name',
    continue: 'Continue',
    createAccount: 'Create Account',
    welcomeBack: 'Welcome Back',
    signIn: 'Sign In',
    signOut: 'Sign Out',
    signOutConfirmTitle: 'Sign Out',
    signOutConfirmMessage: 'Are you sure you want to sign out?',
    forgotPassword: 'Forgot password?',
    orContinueWith: 'Or continue with',
    verifyEmail: 'Verify Your Email',
    verifyEmailSubtitle: "We've sent a 6-digit verification code to",
    enterCode: 'Enter the code',
    resendCode: 'Resend Code',
    codeSent: 'A new verification code has been sent to your email.',
    codeExpired: 'This verification code has expired. Please request a new one.',
    invalidCode: 'The verification code you entered is incorrect.',
    emailVerified: 'Email Verified!',
    emailVerifiedSubtitle: 'Your email has been successfully verified. You can now start using SouqJari.',
    getStarted: 'Get Started',
    passwordReset: 'Password Reset!',
    passwordResetSubtitle: 'Your password has been successfully reset. You can now sign in with your new password.',
    newPassword: 'New Password',
    newPasswordPlaceholder: 'Create a new password',
    setNewPassword: 'Set New Password',
    passwordRequirements: {
      title: 'Password must contain:',
      minLength: 'At least 6 characters',
      uppercase: 'One uppercase letter',
      lowercase: 'One lowercase letter',
      number: 'One number',
    },
    oauthError: 'There was a problem signing in. Please try again.',
    signInMethod: 'Sign In Method',
    signInMethodMessage: 'This account was created using {{provider}}. Please use the {{provider}} button to sign in.',
  },
  tabs: {
    home: 'Home',
    chats: 'Chats',
    post: 'Post',
    favorites: 'Favorites',
    myListings: 'My Listings',
  },
  home: {
    greeting: 'Welcome to SouqJari',
    searchPlaceholder: 'Search listings...',
    categories: 'Categories',
    recentlyViewed: 'Recently Viewed',
    noRecentlyViewed: 'No recently viewed listings',
    browseListings: 'Browse Listings',
  },
  listings: {
    myListings: 'My Listings',
    noListings: 'No Listings Yet',
    noListingsSubtext: 'Start selling by creating your first listing',
    createFirst: 'Create Your First Listing',
    createListing: 'Create Listing',
    active: 'Active',
    sold: 'Sold',
    inactive: 'Inactive',
    deleted: 'Deleted',
    all: 'All',
    markAsSold: 'Mark as Sold',
    markAsActive: 'Mark as Active',
    deactivate: 'Deactivate',
    restore: 'Restore',
    deletePermanently: 'Delete Permanently',
    deleteConfirmTitle: 'Delete Listing?',
    deleteConfirmMessage: 'This listing will be moved to trash. You can restore it within 30 days.',
    permanentDeleteConfirmTitle: 'Delete Permanently?',
    permanentDeleteConfirmMessage: 'This action cannot be undone. The listing will be permanently deleted.',
    statusUpdated: 'Listing status updated',
    listingDeleted: 'Listing deleted',
    listingRestored: 'Listing restored',
    viewListing: 'View Listing',
    editListing: 'Edit Listing',
    postedBy: 'Posted by',
    memberSince: 'Member since',
    viewProfile: 'View Profile',
    contactSeller: 'Contact Seller',
    startChat: 'Start Chat',
    callSeller: 'Call',
    whatsappSeller: 'WhatsApp',
    price: 'Price',
    free: 'Free',
    negotiable: 'Negotiable',
    location: 'Location',
    description: 'Description',
    noDescription: 'No description provided',
    category: 'Category',
    posted: 'Posted',
    updated: 'Updated',
    views: 'views',
    favorites: 'favorites',
    shareError: 'Unable to share listing',
  },
  chat: {
    messages: 'Messages',
    noConversations: 'No Conversations Yet',
    noConversationsSubtext: 'Start chatting with sellers by visiting a listing and tapping "Chat"',
    startChatting: 'Start Chatting',
    browseListings: 'Browse Listings',
    typeMessage: 'Type a message...',
    send: 'Send',
    sending: 'Sending...',
    sent: 'Sent',
    delivered: 'Delivered',
    read: 'Read',
    voiceMessage: 'Voice message',
    holdToRecord: 'Hold to record',
    releaseToSend: 'Release to send',
    recording: 'Recording...',
    tapToPlay: 'Tap to play',
    today: 'Today',
    yesterday: 'Yesterday',
    online: 'Online',
    offline: 'Offline',
    typing: 'typing...',
    selectConversations: 'Select',
    deleteConversations: 'Delete',
    deleteConversationsConfirm: 'Delete {{count}} conversation(s)?',
    signInRequired: 'Sign In Required',
    signInRequiredSubtext: 'Please sign in to view your messages',
    listingDeleted: 'This listing has been deleted',
    listingUnavailable: 'Listing unavailable',
  },
  favorites: {
    favorites: 'Favorites',
    noFavorites: 'No Favorites Yet',
    noFavoritesSubtext: 'Save listings you like by tapping the heart icon',
    browseNow: 'Browse Now',
    removeFavorite: 'Remove from Favorites',
    addFavorite: 'Add to Favorites',
    signInRequired: 'Sign In Required',
    signInRequiredSubtext: 'Please sign in to view your favorites',
  },
  post: {
    postListing: 'Post a Listing',
    titlePlaceholder: 'Title...',
    titleLabel: 'Listing Title',
    selectCategory: 'Select a Category',
    categorySelected: '{{category}} › {{subcategory}}',
    continue: 'Continue',
    missingTitle: 'Please enter a title for your listing',
    missingCategory: 'Please select a category',
  },
  productDetails: {
    listingDetails: 'Listing Details',
    description: 'Description',
    descriptionPlaceholder: 'Describe your item...',
    price: 'Price',
    pricePlaceholder: 'Enter price',
    currency: 'Currency',
    location: 'Location',
    locationPlaceholder: 'Select location',
    selectLocation: 'Select Location',
    photos: 'Photos',
    addPhotos: 'Add Photos',
    photoLimit: '{{current}}/{{max}} photos',
    removePhoto: 'Remove',
    contactInfo: 'Contact Information',
    phoneNumber: 'Phone Number',
    phonePlaceholder: 'Enter phone number',
    whatsappNumber: 'WhatsApp Number',
    whatsappPlaceholder: 'Enter WhatsApp number',
    sameAsPhone: 'Same as phone number',
    postListing: 'Post Listing',
    posting: 'Posting...',
    listingCreated: 'Success!',
    listingCreatedSubtext: 'Your listing has been created',
    noImages: 'No Images Added',
    noImagesMessage: 'Images boost views and drive sales. Are you sure you want to post without images?',
    addImages: 'Add Images',
    postAnyway: 'Post Anyway',
    noContact: 'No Contact Information',
    noContactMessage: "Buyers won't be able to contact you directly. They can still use in-app chat. Continue?",
    draft: 'Draft',
    draftFound: 'Draft Found',
    draftFoundMessage: 'You have an unsaved draft. Would you like to restore it?',
    restoreDraft: 'Restore Draft',
    discardDraft: 'Discard',
    saveDraft: 'Save Draft',
    editListing: 'Edit Listing',
    updateListing: 'Update Listing',
    updating: 'Updating...',
    listingUpdated: 'Listing Updated',
    noChanges: 'No Changes',
    discardChanges: 'Discard Changes?',
    discardChangesMessage: 'You have unsaved changes. Are you sure you want to go back?',
  },
  profile: {
    profile: 'Profile',
    editProfile: 'Edit Profile',
    personalDetails: 'Personal Details',
    displayName: 'Display Name',
    displayNamePlaceholder: 'Enter your name',
    email: 'Email',
    emailReadOnly: 'Email cannot be changed',
    phoneNumber: 'Phone Number',
    phonePlaceholder: 'Enter phone number',
    avatar: 'Profile Photo',
    changePhoto: 'Change Photo',
    removePhoto: 'Remove Photo',
    removePhotoConfirm: 'Are you sure you want to remove your profile photo?',
    saveChanges: 'Save Changes',
    unsavedChanges: 'Unsaved Changes',
    unsavedChangesMessage: 'You have unsaved changes. Are you sure you want to go back?',
    manageAccount: 'Manage Account',
    changePassword: 'Change Password',
    deleteAccount: 'Delete Account',
    deleteAccountWarning: 'This action cannot be undone. All your data will be permanently deleted after 30 days.',
    deleteAccountConfirm: 'Type "DELETE" to confirm',
    typeDelete: 'DELETE',
    enterPassword: 'Enter your password to confirm',
    accountDeleted: 'Your account has been scheduled for deletion',
    oauthPasswordNote: 'You signed in with {{provider}}. Password change is not available.',
    sellerProfile: 'Seller Profile',
    noListings: 'No listings yet',
    sellerNoListings: 'This seller has no active listings',
    listings: 'Listings',
    ratings: 'Ratings',
    ratingsComingSoon: 'Ratings coming soon',
    joinedDate: 'Joined {{date}}',
    daysOnPlatform: '{{count}} day on SouqJari',
    daysOnPlatform_plural: '{{count}} days on SouqJari',
    monthsOnPlatform: '{{count}} month on SouqJari',
    monthsOnPlatform_plural: '{{count}} months on SouqJari',
    yearsOnPlatform: '{{count}} yr on SouqJari',
    yearsOnPlatform_plural: '{{count}} yrs on SouqJari',
  },
  settings: {
    settings: 'Settings',
    account: 'Account',
    preferences: 'Preferences',
    appTheme: 'App Theme',
    themeLight: 'Light',
    themeDark: 'Dark',
    themeSystem: 'System',
    language: 'Language',
    languageArabic: 'العربية',
    languageEnglish: 'English',
    notifications: 'Notifications',
    notificationPreferences: 'Notification Preferences',
    comingSoon: 'Coming Soon',
    help: 'Help',
    helpCenter: 'Help Center',
    privacyPolicy: 'Privacy Policy',
    termsOfUse: 'Terms of Use',
    version: 'Version',
  },
  search: {
    search: 'Search',
    searchPlaceholder: 'Search listings...',
    recentSearches: 'Recent Searches',
    clearRecent: 'Clear',
    noResults: 'No Results',
    noResultsFor: 'No results for "{{query}}"',
    tryDifferent: 'Try a different search term',
    filters: 'Filters',
    sortBy: 'Sort By',
    sortNewest: 'Newest First',
    sortPriceAsc: 'Price: Low to High',
    sortPriceDesc: 'Price: High to Low',
    priceRange: 'Price Range',
    minPrice: 'Min',
    maxPrice: 'Max',
    applyFilters: 'Apply Filters',
    clearFilters: 'Clear Filters',
    resultsCount: '{{count}} results',
  },
  location: {
    selectLocation: 'Select Location',
    currentLocation: 'Current Location',
    detectingLocation: 'Detecting location...',
    locationDetected: 'Location detected',
    locationError: 'Could not detect location',
    searchLocation: 'Search location...',
    nearYou: 'Near You',
    allSyria: 'All Syria',
    radius: 'Radius',
    km: 'km',
    confirmLocation: 'Confirm Location',
    changeLocation: 'Change Location',
  },
  alerts: {
    error: 'Error',
    success: 'Success',
    warning: 'Warning',
    info: 'Info',
    networkError: 'Network Error',
    networkErrorMessage: 'Please check your internet connection and try again.',
    sessionExpired: 'Session Expired',
    sessionExpiredMessage: 'Please sign in again.',
    permissionDenied: 'Permission Denied',
    cameraPermission: 'Camera access is required to take photos.',
    locationPermission: 'Location access is required for this feature.',
    microphonePermission: 'Microphone access is required to record voice messages.',
    storagePermission: 'Storage access is required to save files.',
  },
  errors: {
    somethingWentWrong: 'Something went wrong',
    tryAgain: 'Try Again',
    pageNotFound: 'Page not found',
    goHome: 'Go Home',
    noInternet: 'No internet connection',
    serverError: 'Server error. Please try again later.',
    timeout: 'Request timed out. Please try again.',
    unauthorized: 'Please sign in to continue.',
    forbidden: 'You do not have permission to access this.',
  },
  time: {
    justNow: 'Just now',
    minutesAgo: '{{count}}m ago',
    hoursAgo: '{{count}}h ago',
    daysAgo: '{{count}}d ago',
    weeksAgo: '{{count}}w ago',
    monthsAgo: '{{count}}mo ago',
    yearsAgo: '{{count}}y ago',
    today: 'today',
    yesterday: 'yesterday',
    yesterdayAt: 'Yesterday {{time}}',
    overAMonthAgo: 'over a month ago',
    overAYearAgo: 'over a year ago',
  },
  validation: {
    required: 'This field is required',
    invalidEmail: 'Please enter a valid email address',
    invalidPhone: 'Please enter a valid phone number',
    passwordTooShort: 'Password must be at least 6 characters',
    passwordsDontMatch: 'Passwords do not match',
    priceMustBeNumber: 'Price must be a valid number',
    titleTooShort: 'Title must be at least 3 characters',
    titleTooLong: 'Title must be less than 100 characters',
    descriptionTooLong: 'Description must be less than 5000 characters',
  },
};

export default en;
