// English translations (fallback)
import { TranslationResources } from './types';

const en: TranslationResources = {
  common: {
    loading: 'Loading...',
    error: 'Error',
    retry: 'Try Again',
    cancel: 'Cancel',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    search: 'Search',
    noResults: 'No results found',
    signIn: 'Sign In',
    signUp: 'Sign Up',
    signInRequired: 'Sign In Required',
    comingSoon: 'Coming Soon',
    ok: 'OK',
    yes: 'Yes',
    no: 'No',
    confirm: 'Confirm',
    close: 'Close',
    back: 'Back',
    next: 'Next',
    done: 'Done',
    submit: 'Submit',
    continue: 'Continue',
    viewAll: 'View All',
    seeAll: 'See All',
    share: 'Share',
    report: 'Report',
    block: 'Block',
    unblock: 'Unblock',
    moreOptions: 'More Options',
    selectOption: 'Select an option',
    required: 'Required',
    optional: 'Optional',
    item: 'item',
    items: 'items',
  },

  auth: {
    loginOrSignup: 'Log in or Sign up',
    emailAddress: 'Email Address',
    enterEmail: 'Enter your email address',
    invalidEmail: 'Please enter a valid email address',
    password: 'Password',
    enterPassword: 'Enter your password',
    createPassword: 'Create a password',
    forgotPassword: 'Forgot password?',
    forgotPasswordTitle: 'Forgot Password?',
    forgotPasswordSubtitle: "Enter your email and we'll send you a verification code.",
    sendCode: 'Send Code',
    resetPassword: 'Reset Password',
    newPassword: 'New Password',
    newPasswordSubtitle: 'Create a strong password for your account.',
    createAccount: 'Create Account',
    welcomeBack: 'Welcome Back',
    setUpAccount: 'Set up your account to get started',
    enterPasswordToSignIn: 'Enter your password to sign in',
    yourName: 'Your Name',
    enterFullName: 'Enter your full name',
    termsFooter: 'By continuing, you agree to our',
    termsOfService: 'Terms of Service',
    privacyPolicy: 'Privacy Policy',
    and: 'and',
    verifyEmail: 'Verify Your Email',
    verificationCodeSent: "We've sent a 6-digit verification code to",
    enterCode: 'Enter Code',
    verifyCode: 'Verify Code',
    resendCode: 'Resend Code',
    didntReceiveCode: "Didn't receive the code? Resend",
    backToSignIn: 'Back to Sign In',
    emailVerified: 'Email Verified!',
    emailVerifiedSubtitle: 'Your email has been successfully verified. You can now start using SouqJari.',
    getStarted: 'Get Started',
    passwordReset: 'Password Reset!',
    passwordResetSubtitle: 'Your password has been successfully reset. You can now sign in with your new password.',
    signInMethod: 'Sign In Method',
    oauthOnlyMessage: 'This account was created using {{provider}}. Please use the "{{provider}}" button below to sign in.',
    accountNotFound: 'Account Not Found',
    accountNotFoundMessage: 'No account found with this email address.',
    invalidCode: 'Invalid Code',
    invalidCodeMessage: 'The code you entered is invalid or has expired. Please try again.',
    codeSent: 'Code Sent',
    codeSentMessage: 'A new verification code has been sent to your email.',
    passwordMinLength: 'Password must be at least 6 characters',
    enterName: 'Please enter your name',
    change: 'Change',
  },

  tabs: {
    home: 'Home',
    chats: 'Chats',
    post: 'Post',
    favorites: 'Favorites',
    myListings: 'My Listings',
  },

  home: {
    searchPlaceholder: 'Search all listings...',
    allCategories: 'All Categories',
    recentlyViewed: 'Recently Viewed',
    clearAll: 'Clear All',
    noRecentlyViewed: 'No recently viewed listings',
  },

  listing: {
    price: 'Price',
    description: 'Description',
    location: 'Location',
    openInMaps: 'Open in Maps',
    contactSeller: 'Contact Seller',
    chat: 'Chat',
    call: 'Call',
    whatsapp: 'WhatsApp',
    sold: 'Sold',
    unavailable: 'Unavailable',
    listingNotFound: 'Listing not found',
    goBack: 'Go Back',
    signInToChat: 'Please sign in to chat with the seller',
    cantChatOwnListing: "You can't chat with yourself on your own listing",
    failedToStartConversation: 'Failed to start conversation',
    failedToLoad: 'Failed to load listing',
    listedBy: 'Listed by',
    activeListings: 'active listings',
    moreFromSeller: 'More from this seller',
    viewSellerProfile: 'View Profile',
    shareListingMessage: 'Check out this listing: {{title}}',
  },

  createListing: {
    createListing: 'Create Listing',
    editListing: 'Edit Listing',
    title: 'Title',
    titlePlaceholder: 'What are you selling?',
    descriptionPlaceholder: 'Describe your item in detail...',
    pricePlaceholder: 'Enter price',
    category: 'Category',
    subcategory: 'Subcategory',
    selectCategory: 'Select a category',
    selectSubcategory: 'Select a subcategory',
    addPhotos: 'Add Photos',
    addMorePhotos: 'Add More Photos',
    photoLimit: '{{current}}/{{max}} photos',
    setLocation: 'Set Location',
    changeLocation: 'Change Location',
    contactInfo: 'Contact Information',
    phoneNumber: 'Phone Number',
    whatsappNumber: 'WhatsApp Number',
    sameAsPhone: 'Same as phone number',
    publish: 'Publish Listing',
    saveChanges: 'Save Changes',
    saveDraft: 'Save Draft',
    discardChanges: 'Discard Changes',
    requiredField: 'This field is required',
    listingCreated: 'Listing created successfully!',
    listingUpdated: 'Listing updated successfully!',
    listingDeleted: 'Listing deleted successfully!',
  },

  myListings: {
    noListingsYet: 'No Listings Yet',
    startSelling: 'Start selling by posting your first listing',
    createFirstListing: 'Create Your First Listing',
    all: 'All',
    active: 'Active',
    soldStatus: 'Sold',
    hidden: 'Hidden',
    noActiveListings: "You don't have any active listings",
    noSoldItems: "You haven't sold any items yet",
    noHiddenListings: "You don't have any hidden listings",
    markAsSold: 'Mark as Sold',
    markAsActive: 'Mark as Active',
    hide: 'Hide',
    unhide: 'Unhide',
    deleteListing: 'Delete Listing',
    deleteConfirmTitle: 'Delete Listing',
    deleteConfirmMessage: 'Are you sure you want to delete this listing? This action cannot be undone.',
    restoreListing: 'Restore Listing',
  },

  favorites: {
    noFavoritesYet: 'No Favorites Yet',
    savedListingsAppear: 'Listings you save will appear here',
    browseListings: 'Browse Listings',
    signInToViewFavorites: 'Please sign in to save and view your favorites',
  },

  chats: {
    messages: 'Messages',
    noConversationsYet: 'No Conversations Yet',
    startChatting: 'Start chatting with sellers by visiting a listing and tapping "Chat"',
    browseListingsToChat: 'Browse Listings',
    signInToViewMessages: 'Please sign in to view your messages',
    deleteConversation: 'Delete Conversation',
    deleteConversationConfirm: 'Are you sure you want to delete this conversation?',
    deleteConversations: 'Delete Conversations',
    deleteConversationsConfirm: 'Are you sure you want to delete {{count}} conversations?',
    typeMessage: 'Type a message...',
    send: 'Send',
    voiceMessage: 'Voice Message',
    startConversation: 'Start a conversation...',
    now: 'Now',
    user: 'User',
    listing: 'Listing',
  },

  user: {
    account: 'Account',
    signInToAccess: 'Sign in to access your account settings',
    dontHaveAccount: "Don't have an account? Sign Up",
    memberSince: 'Member since',
    accountSettings: 'ACCOUNT SETTINGS',
    manageAccount: 'Manage Account',
    passwordDeleteAccount: 'Password, delete account',
    appSettings: 'APP SETTINGS',
    appTheme: 'App Theme',
    notificationPreferences: 'Notification Preferences',
    pushNotificationsEmail: 'Push notifications, email alerts',
    supportLegal: 'SUPPORT & LEGAL',
    help: 'Help',
    faqsSupport: 'FAQs and support',
    logOut: 'Log Out',
    logOutConfirm: 'Are you sure you want to log out?',
    failedToLogOut: 'Failed to log out. Please try again.',
    themeLight: 'Light',
    themeDark: 'Dark',
    themeSystem: 'System Settings',
  },

  personalDetails: {
    personalDetails: 'Personal Details',
    profilePhoto: 'Profile Photo',
    changePhoto: 'Change Photo',
    displayName: 'Display Name',
    email: 'Email',
    phone: 'Phone Number',
    saveProfile: 'Save Profile',
    profileUpdated: 'Profile updated successfully!',
    profileUpdateFailed: 'Failed to update profile. Please try again.',
  },

  manageAccount: {
    changePassword: 'Change Password',
    currentPassword: 'Current Password',
    newPasswordField: 'New Password',
    confirmPassword: 'Confirm Password',
    passwordsDontMatch: "Passwords don't match",
    passwordChanged: 'Password changed successfully!',
    deleteAccount: 'Delete Account',
    deleteAccountWarning: 'This action is permanent and cannot be undone. All your data will be deleted.',
    deleteAccountConfirm: 'Are you sure you want to delete your account?',
    typeDeleteToConfirm: 'Type "DELETE" to confirm',
    accountDeleted: 'Account deleted successfully',
  },

  search: {
    searchListings: 'Search listings...',
    recentSearches: 'Recent Searches',
    clearRecentSearches: 'Clear Recent Searches',
    noResultsFor: 'No results found for "{{query}}"',
    tryDifferentKeywords: 'Try different keywords or browse categories',
    filterResults: 'Filter Results',
    sortBy: 'Sort By',
    priceRange: 'Price Range',
    minPrice: 'Min Price',
    maxPrice: 'Max Price',
    applyFilters: 'Apply Filters',
    clearFilters: 'Clear Filters',
    resultsFound: '{{count}} results found',
  },

  location: {
    selectLocation: 'Select Location',
    currentLocation: 'Current Location',
    useCurrentLocation: 'Use Current Location',
    searchLocation: 'Search location...',
    locationPermission: 'Location Permission',
    locationPermissionMessage: 'We need your location to show nearby listings',
    enableLocation: 'Enable Location',
    radius: 'Radius',
    km: 'km',
    allLocations: 'All Locations',
    syria: 'Syria',
    nearby: 'Nearby',
  },

  categories: {
    buyAndSell: 'Buy & Sell',
    cars: 'Cars',
    realEstate: 'Real Estate',
    jobs: 'Jobs',
    services: 'Services',
    pets: 'Pets',
    electronics: 'Electronics',
    furniture: 'Furniture',
    clothing: 'Clothing',
    books: 'Books',
    phones: 'Phones',
    computers: 'Computers',
    homeAppliances: 'Home Appliances',
    toysAndGames: 'Toys & Games',
    sportsEquipment: 'Sports Equipment',
    other: 'Other',
    carsAndTrucks: 'Cars & Trucks',
    motorcycles: 'Motorcycles',
    vehicleParts: 'Vehicle Parts',
    forRent: 'For Rent',
    forSale: 'For Sale',
    accounting: 'Accounting',
    customerService: 'Customer Service',
    healthcare: 'Healthcare',
    sales: 'Sales',
    itAndProgramming: 'IT & Programming',
    homeMaintenance: 'Home Maintenance',
    tutoring: 'Tutoring',
    cleaning: 'Cleaning',
    moving: 'Moving',
    cats: 'Cats',
    dogs: 'Dogs',
    birds: 'Birds',
  },

  errors: {
    somethingWentWrong: 'Something went wrong',
    tryAgain: 'Please try again',
    networkError: 'Network Error',
    checkConnection: 'Please check your internet connection',
    sessionExpired: 'Session Expired',
    pleaseSignInAgain: 'Please sign in again',
    permissionDenied: 'Permission Denied',
    invalidInput: 'Invalid input',
    unableToMakeCall: 'Unable to make phone call',
    whatsappNotInstalled: 'WhatsApp is not installed',
    failedToShare: 'Failed to share',
  },

  time: {
    justNow: 'Just now',
    minuteAgo: '1 minute ago',
    minutesAgo: '{{count}} minutes ago',
    hourAgo: '1 hour ago',
    hoursAgo: '{{count}} hours ago',
    dayAgo: '1 day ago',
    daysAgo: '{{count}} days ago',
    weekAgo: '1 week ago',
    weeksAgo: '{{count}} weeks ago',
    monthAgo: '1 month ago',
    monthsAgo: '{{count}} months ago',
    yearAgo: '1 year ago',
    yearsAgo: '{{count}} years ago',
  },
};

export default en;
