import { TranslationKeys } from './types';

const en: TranslationKeys = {
  common: {
    loading: 'Loading...',
    error: 'An error occurred',
    retry: 'Retry',
    cancel: 'Cancel',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    search: 'Search',
    noResults: 'No results found',
    confirm: 'Confirm',
    yes: 'Yes',
    no: 'No',
    ok: 'OK',
    done: 'Done',
    next: 'Next',
    back: 'Back',
    close: 'Close',
    share: 'Share',
    refresh: 'Refresh',
    seeAll: 'See All',
    showMore: 'Show More',
    showLess: 'Show Less',
    stay: 'Stay',
    discard: 'Discard',
    saveChanges: 'Save Changes',
    remove: 'Remove',
    comingSoon: 'Coming Soon',
    comingSoonMessage: '{{feature}} is coming soon!',
    item: 'item',
    items: 'items',
    keep: 'Keep',
    options: 'Options',
  },
  auth: {
    loginOrSignup: 'Log in or Sign up',
    emailPlaceholder: 'Enter your email address',
    emailLabel: 'Email Address',
    passwordPlaceholder: 'Enter your password',
    passwordLabel: 'Password',
    namePlaceholder: 'Enter your full name',
    nameLabel: 'Your Name',
    continue: 'Continue',
    createAccount: 'Create Account',
    welcomeBack: 'Welcome Back',
    signIn: 'Sign In',
    signOut: 'Sign Out',
    signOutConfirmTitle: 'Sign Out',
    signOutConfirmMessage: 'Are you sure you want to sign out?',
    forgotPassword: 'Forgot password?',
    orContinueWith: 'Or continue with',
    verifyEmail: 'Verify Your Email',
    verifyEmailSubtitle: "We've sent a 6-digit verification code to",
    enterCode: 'Enter the code',
    resendCode: 'Resend Code',
    codeSent: 'A new verification code has been sent to your email.',
    codeExpired: 'This verification code has expired. Please request a new one.',
    invalidCode: 'The verification code you entered is incorrect.',
    emailVerified: 'Email Verified!',
    emailVerifiedSubtitle: 'Your email has been successfully verified. You can now start using SouqJari.',
    getStarted: 'Get Started',
    passwordReset: 'Password Reset!',
    passwordResetSubtitle: 'Your password has been successfully reset. You can now sign in with your new password.',
    newPassword: 'New Password',
    newPasswordPlaceholder: 'Create a new password',
    setNewPassword: 'Set New Password',
    passwordRequirements: {
      title: 'Password must contain:',
      minLength: 'At least 6 characters',
      uppercase: 'One uppercase letter',
      lowercase: 'One lowercase letter',
      number: 'One number',
    },
    oauthError: 'There was a problem signing in. Please try again.',
    signInMethod: 'Sign In Method',
    signInMethodMessage: 'This account was created using {{provider}}. Please use the {{provider}} button to sign in.',
    noAccountSignUp: "Don't have an account? Sign up",
    currentPassword: 'Current Password',
    currentPasswordPlaceholder: 'Enter current password',
    newPasswordPlaceholder: 'Enter new password',
    confirmNewPassword: 'Confirm New Password',
    confirmNewPasswordPlaceholder: 'Confirm new password',
    passwordMinLength: 'Password must be at least 6 characters',
    updatePassword: 'Update Password',
    passwordUpdated: 'Your password has been updated.',
    currentPasswordIncorrect: 'Current password is incorrect.',
    passwordsDoNotMatch: 'New passwords do not match.',
    cannotChangePassword: 'Cannot Change Password',
    cannotChangePasswordMessage: 'You signed in with Google or Facebook. To set a password, please use the "Forgot Password" option on the login screen.',
  },
  tabs: {
    home: 'Home',
    chats: 'Chats',
    post: 'Post',
    favorites: 'Favorites',
    myListings: 'My Listings',
  },
  home: {
    greeting: 'Welcome to SouqJari',
    searchPlaceholder: 'Search listings...',
    categories: 'Categories',
    recentlyViewed: 'Recently Viewed',
    noRecentlyViewed: 'No Recently Viewed',
    noRecentlyViewedSubtext: 'Listings you view will appear here',
    clearRecentlyViewed: 'Clear',
    browseListings: 'Browse Listings',
  },
  categories: {
    // Main categories
    buySell: 'Buy & Sell',
    cars: 'Cars',
    realEstate: 'Real Estate',
    jobs: 'Jobs',
    services: 'Services',
    pets: 'Pets',
    // Buy & Sell subcategories
    electronics: 'Electronics',
    furniture: 'Furniture',
    clothing: 'Clothing',
    books: 'Books',
    phones: 'Phones',
    computers: 'Computers',
    homeAppliances: 'Home Appliances',
    toysGames: 'Toys & Games',
    sportsEquipment: 'Sports Equipment',
    // Cars subcategories
    carsTrucks: 'Cars & Trucks',
    motorcycles: 'Motorcycles',
    vehicleParts: 'Vehicle Parts',
    // Real Estate subcategories
    forRent: 'For Rent',
    forSale: 'For Sale',
    // Jobs subcategories
    accounting: 'Accounting',
    customerService: 'Customer Service',
    healthcare: 'Healthcare',
    sales: 'Sales',
    itProgramming: 'IT & Programming',
    // Services subcategories
    homeMaintenance: 'Home Maintenance',
    tutoring: 'Tutoring',
    cleaning: 'Cleaning',
    moving: 'Moving',
    // Pets subcategories
    cats: 'Cats',
    dogs: 'Dogs',
    birds: 'Birds',
    // Common
    other: 'Other',
  },
  listings: {
    myListings: 'My Listings',
    noListings: 'No Listings Yet',
    noListingsSubtext: 'Start selling by creating your first listing',
    noListingsSubtitle: 'Start selling by creating your first listing',
    createFirst: 'Create Your First Listing',
    createListing: 'Create Listing',
    active: 'Active',
    sold: 'Sold',
    inactive: 'Inactive',
    deleted: 'Deleted',
    all: 'All',
    markAsSold: 'Mark as Sold',
    markAsActive: 'Mark as Active',
    deactivate: 'Deactivate',
    restore: 'Restore',
    deletePermanently: 'Delete Permanently',
    deleteConfirmTitle: 'Delete Listing?',
    deleteConfirmMessage: 'This listing will be moved to trash. You can restore it within 30 days.',
    permanentDeleteConfirmTitle: 'Delete Permanently?',
    permanentDeleteConfirmMessage: 'This action cannot be undone. The listing will be permanently deleted.',
    statusUpdated: 'Listing status updated',
    listingDeleted: 'Listing deleted',
    listingRestored: 'Listing restored',
    viewListing: 'View Listing',
    editListing: 'Edit Listing',
    postedBy: 'Posted by',
    memberSince: 'Member since',
    viewProfile: 'View Profile',
    contactSeller: 'Contact Seller',
    startChat: 'Start Chat',
    callSeller: 'Call',
    whatsappSeller: 'WhatsApp',
    price: 'Price',
    free: 'Free',
    negotiable: 'Negotiable',
    location: 'Location',
    description: 'Description',
    noDescription: 'No description provided',
    category: 'Category',
    posted: 'Posted',
    updated: 'Updated',
    views: 'views',
    favorites: 'favorites',
    shareError: 'Unable to share listing',
    // Sign in required
    signInRequired: 'Sign In Required',
    signInRequiredSubtitle: 'Please sign in to view your listings',
    // Filter tabs
    filterAll: 'All',
    filterActive: 'Active',
    filterSold: 'Sold',
    filterHidden: 'Hidden',
    // Empty state messages for filters
    noListingsInFilter: 'No listings in this filter',
    noActive: 'No active listings',
    noSold: 'No sold listings',
    noInactive: 'No hidden listings',
    // Status badges
    statusActive: 'Active',
    statusSold: 'Sold',
    statusHidden: 'Hidden',
    statusUnavailable: 'Unavailable',
    // Action buttons
    actionEdit: 'Edit',
    actionMarkSold: 'Mark Sold',
    actionRemove: 'Remove',
    actionReactivate: 'Reactivate',
    actionRestore: 'Restore',
    actionDeleteForever: 'Delete Forever',
    // Confirmation dialogs
    removeConfirmTitle: 'Remove Listing?',
    removeConfirmMessage: 'This listing will be hidden from buyers. You can restore it later.',
    deleteForeverConfirmTitle: 'Delete Forever?',
    deleteForeverConfirmMessage: 'This action cannot be undone. The listing will be permanently deleted.',
    markSoldConfirmTitle: 'Mark as Sold?',
    markSoldConfirmMessage: 'This will mark your listing as sold.',
    // Success/error messages
    listingRemoved: 'Listing removed',
    updateFailed: 'Update failed. Please try again.',
  },
  chat: {
    messages: 'Messages',
    noConversations: 'No Conversations Yet',
    noConversationsSubtext: 'Start chatting with sellers by visiting a listing and tapping "Chat"',
    startChatting: 'Start Chatting',
    browseListings: 'Browse Listings',
    typeMessage: 'Type a message...',
    send: 'Send',
    sending: 'Sending...',
    sent: 'Sent',
    delivered: 'Delivered',
    read: 'Read',
    voiceMessage: 'Voice message',
    holdToRecord: 'Hold to record',
    releaseToSend: 'Release to send',
    recording: 'Recording...',
    tapToPlay: 'Tap to play',
    today: 'Today',
    yesterday: 'Yesterday',
    online: 'Online',
    offline: 'Offline',
    typing: 'typing...',
    selectConversations: 'Select',
    deleteConversations: 'Delete',
    deleteConversationsConfirm: 'Delete {{count}} conversation(s)?',
    signInRequired: 'Sign In Required',
    signInRequiredSubtext: 'Please sign in to view your messages',
    listingDeleted: 'This listing has been deleted',
    listingUnavailable: 'Listing unavailable',
  },
  favorites: {
    favorites: 'Favorites',
    noFavorites: 'No Favorites Yet',
    noFavoritesSubtext: 'Save listings you like by tapping the heart icon',
    browseNow: 'Browse Now',
    removeFavorite: 'Remove',
    addFavorite: 'Add to Favorites',
    signInRequired: 'Sign In Required',
    signInRequiredSubtext: 'Please sign in to view your favorites',
    itemSold: 'Item Sold',
    itemUnavailable: 'Item Unavailable',
    removeUnavailableMessage: 'This listing is no longer available. Would you like to remove it from your favorites?',
  },
  post: {
    postListing: 'Post a Listing',
    titlePlaceholder: 'Title...',
    titleLabel: 'Listing Title',
    selectCategory: 'Select a Category',
    categorySelected: '{{category}} › {{subcategory}}',
    continue: 'Continue',
    missingTitle: 'Please enter a title for your listing',
    missingCategory: 'Please select a category',
  },
  productDetails: {
    listingDetails: 'Listing Details',
    description: 'Description',
    descriptionPlaceholder: 'Describe your item...',
    price: 'Price',
    pricePlaceholder: 'Enter price',
    currency: 'Currency',
    location: 'Location',
    locationPlaceholder: 'Select location',
    selectLocation: 'Select Location',
    photos: 'Photos',
    addPhotos: 'Add Photos',
    photoLimit: '{{current}}/{{max}} photos',
    removePhoto: 'Remove',
    contactInfo: 'Contact Information',
    phoneNumber: 'Phone Number',
    phonePlaceholder: 'Enter phone number',
    whatsappNumber: 'WhatsApp Number',
    whatsappPlaceholder: 'Enter WhatsApp number',
    sameAsPhone: 'Same as phone number',
    postListing: 'Post Listing',
    posting: 'Posting...',
    listingCreated: 'Success!',
    listingCreatedSubtext: 'Your listing has been created',
    noImages: 'No Images Added',
    noImagesMessage: 'Images boost views and drive sales. Are you sure you want to post without images?',
    addImages: 'Add Images',
    postAnyway: 'Post Anyway',
    noContact: 'No Contact Information',
    noContactMessage: "Buyers won't be able to contact you directly. They can still use in-app chat. Continue?",
    draft: 'Draft',
    draftFound: 'Draft Found',
    draftFoundMessage: 'You have an unsaved draft. Would you like to restore it?',
    restoreDraft: 'Restore Draft',
    discardDraft: 'Discard',
    saveDraft: 'Save Draft',
    editListing: 'Edit Listing',
    updateListing: 'Update Listing',
    updating: 'Updating...',
    listingUpdated: 'Listing Updated',
    noChanges: 'No Changes',
    discardChanges: 'Discard Changes?',
    discardChangesMessage: 'You have unsaved changes. Are you sure you want to go back?',
  },
  profile: {
    profile: 'Profile',
    editProfile: 'Edit Profile',
    personalDetails: 'Personal Details',
    displayName: 'Display Name',
    displayNamePlaceholder: 'Enter your name',
    email: 'Email',
    emailReadOnly: 'Email cannot be changed',
    phoneNumber: 'Phone Number',
    phonePlaceholder: 'Enter phone number',
    avatar: 'Profile Photo',
    changePhoto: 'Change Photo',
    removePhoto: 'Remove Photo',
    removePhotoConfirm: 'Are you sure you want to remove your profile photo?',
    saveChanges: 'Save Changes',
    unsavedChanges: 'Unsaved Changes',
    unsavedChangesMessage: 'You have unsaved changes. Are you sure you want to go back?',
    manageAccount: 'Manage Account',
    changePassword: 'Change Password',
    deleteAccount: 'Delete Account',
    deleteAccountWarning: 'This action cannot be undone. All your data will be permanently deleted after 30 days.',
    deleteAccountConfirm: 'Type "DELETE" to confirm',
    typeDelete: 'DELETE',
    enterPassword: 'Enter your password to confirm',
    accountDeleted: 'Your account has been scheduled for deletion',
    oauthPasswordNote: 'You signed in with {{provider}}. Password change is not available.',
    sellerProfile: 'Seller Profile',
    noListings: 'No listings yet',
    sellerNoListings: 'This seller has no active listings',
    listings: 'Listings',
    ratings: 'Ratings',
    ratingsComingSoon: 'Ratings coming soon',
    joinedDate: 'Joined {{date}}',
    daysOnPlatform: '{{count}} day on SouqJari',
    daysOnPlatform_plural: '{{count}} days on SouqJari',
    monthsOnPlatform: '{{count}} month on SouqJari',
    monthsOnPlatform_plural: '{{count}} months on SouqJari',
    yearsOnPlatform: '{{count}} yr on SouqJari',
    yearsOnPlatform_plural: '{{count}} yrs on SouqJari',
    enterName: 'Enter your name',
    enterPhone: 'Enter phone number',
    noEmailSet: 'No email set',
    emailSecurityNote: 'Email is used for account security and cannot be changed',
    profileUpdated: 'Profile updated successfully',
    updateFailed: 'Failed to update profile',
    memberSince: 'Member since {{date}}',
    permissionRequired: 'Permission Required',
    photoLibraryPermission: 'Please allow access to your photo library to change your profile photo.',
    avatarUpdateFailed: 'Failed to update avatar',
    avatarUploadFailed: 'Failed to upload avatar',
    uploadFailed: 'Upload Failed',
    removePhotoFailed: 'Failed to remove photo',
  },
  settings: {
    settings: 'Settings',
    account: 'Account',
    preferences: 'Preferences',
    appTheme: 'App Theme',
    themeLight: 'Light',
    themeDark: 'Dark',
    themeSystem: 'System',
    themeLightSubtitle: 'Always use light theme',
    themeDarkSubtitle: 'Always use dark theme',
    themeSystemSubtitle: 'Match device settings',
    language: 'Language',
    languageArabic: 'العربية',
    languageEnglish: 'English',
    notifications: 'Notifications',
    notificationPreferences: 'Notification Preferences',
    comingSoon: 'Coming Soon',
    help: 'Help',
    helpCenter: 'Help Center',
    privacyPolicy: 'Privacy Policy',
    termsOfUse: 'Terms of Use',
    version: 'Version',
    accountSettings: 'Account Settings',
    appSettings: 'App Settings',
    manageAccount: 'Manage Account',
    manageAccountSubtitle: 'Password, security & deletion',
    security: 'Security',
    changePassword: 'Change Password',
    changePasswordSubtitle: 'Update your password',
    notAvailableSocial: 'Not available for social login',
    dangerZone: 'Danger Zone',
    deleteAccount: 'Delete Account',
    deleteAccountSubtitle: 'Permanently delete your account and data',
    supportLegal: 'Support & Legal',
    helpSubtitle: 'FAQs and contact support',
    notificationsSubtitle: 'Manage notification preferences',
    logOut: 'Log Out',
    logOutConfirm: 'Are you sure you want to log out?',
    logOutFailed: 'Failed to log out. Please try again.',
    signInPrompt: 'Sign in to access your account settings',
  },
  search: {
    search: 'Search',
    searchPlaceholder: 'Search listings...',
    recentSearches: 'Recent Searches',
    clearRecent: 'Clear',
    noResults: 'No Results',
    noResultsFor: 'No results for "{{query}}"',
    tryDifferent: 'Try a different search term',
    filters: 'Filters',
    sortBy: 'Sort By',
    sortNewest: 'Newest First',
    sortPriceAsc: 'Price: Low to High',
    sortPriceDesc: 'Price: High to Low',
    priceRange: 'Price Range',
    minPrice: 'Min',
    maxPrice: 'Max',
    applyFilters: 'Apply Filters',
    clearFilters: 'Clear Filters',
    resultsCount: '{{count}} results',
  },
  location: {
    selectLocation: 'Select Location',
    currentLocation: 'Current Location',
    detectingLocation: 'Detecting location...',
    locationDetected: 'Location detected',
    locationError: 'Could not detect location',
    searchLocation: 'Search location...',
    nearYou: 'Near You',
    allSyria: 'All Syria',
    radius: 'Radius',
    km: 'km',
    confirmLocation: 'Confirm Location',
    changeLocation: 'Change Location',
    myLocation: 'My Location',
    useMyLocation: 'Use my current location',
    couldNotGetLocation: 'Could not get your current location. Please try again.',
    permissionRequired: 'Permission Required',
    pleaseAllowLocation: 'Please allow location access to use this feature',
  },
  alerts: {
    error: 'Error',
    success: 'Success',
    warning: 'Warning',
    info: 'Info',
    networkError: 'Network Error',
    networkErrorMessage: 'Please check your internet connection and try again.',
    sessionExpired: 'Session Expired',
    sessionExpiredMessage: 'Please sign in again.',
    permissionDenied: 'Permission Denied',
    cameraPermission: 'Camera access is required to take photos.',
    locationPermission: 'Location access is required for this feature.',
    microphonePermission: 'Microphone access is required to record voice messages.',
    storagePermission: 'Storage access is required to save files.',
  },
  errors: {
    somethingWentWrong: 'Something went wrong',
    tryAgain: 'Try Again',
    pageNotFound: 'Page not found',
    goHome: 'Go Home',
    noInternet: 'No internet connection',
    serverError: 'Server error. Please try again later.',
    timeout: 'Request timed out. Please try again.',
    unauthorized: 'Please sign in to continue.',
    forbidden: 'You do not have permission to access this.',
    unexpected: 'An unexpected error occurred.',
  },
  time: {
    justNow: 'Just now',
    minutesAgo: '{{count}}m ago',
    hoursAgo: '{{count}}h ago',
    daysAgo: '{{count}}d ago',
    weeksAgo: '{{count}}w ago',
    monthsAgo: '{{count}}mo ago',
    yearsAgo: '{{count}}y ago',
    today: 'today',
    yesterday: 'yesterday',
    yesterdayAt: 'Yesterday {{time}}',
    overAMonthAgo: 'over a month ago',
    overAYearAgo: 'over a year ago',
    // Short format for chat list
    now: 'Now',
    minutesShort: '{{count}}m',
    hoursShort: '{{count}}h',
    daysShort: '{{count}}d',
  },
  validation: {
    required: 'This field is required',
    invalidEmail: 'Please enter a valid email address',
    invalidPhone: 'Please enter a valid phone number',
    passwordTooShort: 'Password must be at least 6 characters',
    passwordsDontMatch: 'Passwords do not match',
    priceMustBeNumber: 'Price must be a valid number',
    titleTooShort: 'Title must be at least 3 characters',
    titleTooLong: 'Title must be less than 100 characters',
    descriptionTooLong: 'Description must be less than 5000 characters',
  },
  notifications: {
    title: 'Notifications',
    pushNotifications: 'PUSH NOTIFICATIONS',
    enablePush: 'Enable Push Notifications',
    enablePushSubtitle: 'Receive notifications on your device',
    notificationTypes: 'NOTIFICATION TYPES',
    messages: 'Messages',
    messagesSubtitle: 'When someone sends you a message',
    listingActivity: 'Listing Activity',
    listingActivitySubtitle: 'When your listing gets views or favorites',
    priceDrops: 'Price Drops',
    priceDropsSubtitle: 'When favorited items drop in price',
    promoUpdates: 'Promotions & Updates',
    promoUpdatesSubtitle: 'Special offers and app updates',
    permissionNotice: 'Push notifications require permission. You may need to enable them in your device settings if you haven\'t already.',
  },
  help: {
    title: 'Help & Support',
    contactSupport: 'CONTACT SUPPORT',
    emailSupport: 'Email Support',
    emailSupportSubtitle: 'support@souqjari.com',
    whatsappSupport: 'WhatsApp Support',
    whatsappSupportSubtitle: 'Chat with us directly',
    whatsappComingSoon: 'WhatsApp support will be available soon. For now, please contact us via email.',
    faq: 'FREQUENTLY ASKED QUESTIONS',
    responseTime: 'Response time: Usually within 24 hours',
    faqPostListing: 'How do I post a listing?',
    faqPostListingAnswer: 'To post a listing, tap the "+" button in the center of the bottom navigation bar. Fill in the details about your item including photos, title, description, price, and category. Then tap "Post" to publish your listing.',
    faqEditListing: 'How do I edit my listing?',
    faqEditListingAnswer: 'Go to your profile and tap on "My Listings". Find the listing you want to edit and tap on it. Then tap the edit icon in the top right corner to modify your listing details.',
    faqContactSeller: 'How do I contact a seller?',
    faqContactSellerAnswer: 'When viewing a listing, you can tap the "Chat" button to start a conversation with the seller. You can also call or WhatsApp them using the buttons below the listing photos if they have provided contact information.',
    faqDeleteAccount: 'How do I delete my account?',
    faqDeleteAccountAnswer: 'Go to Settings > Manage Account > Delete Account. You will need to confirm your identity before the account is deleted. Your data will be removed within 30 days.',
    faqDataSafety: 'Is my data safe?',
    faqDataSafetyAnswer: 'Yes, we take data security seriously. Your personal information is encrypted and stored securely. We do not sell your data to third parties. Read our Privacy Policy for more details.',
    faqReportListing: 'How do I report a listing?',
    faqReportListingAnswer: 'When viewing a listing, tap the three dots icon in the top right corner and select "Report". Choose the reason for reporting and submit. Our team will review the report.',
  },
  legal: {
    lastUpdated: 'Last updated: {{date}}',
    // Privacy Policy
    privacyPolicy: 'Privacy Policy',
    privacyIntroTitle: 'Introduction',
    privacyIntroContent: 'SouqJari ("we", "our", or "us") is committed to protecting your privacy. This Privacy Policy explains how we collect, use, and share your personal information when you use our mobile application.',
    privacyInfoCollectTitle: 'Information We Collect',
    privacyInfoCollectContent: '• Account information (email, name, phone number)\n• Profile information (avatar, bio)\n• Listing content (photos, descriptions, prices)\n• Location data (for listing location)\n• Messages between users\n• Device information and usage data',
    privacyHowUseTitle: 'How We Use Your Information',
    privacyHowUseContent: 'We use your information to:\n\n• Provide and improve our services\n• Enable communication between buyers and sellers\n• Personalize your experience\n• Send important notifications\n• Ensure safety and security',
    privacyDataSharingTitle: 'Data Sharing',
    privacyDataSharingContent: 'We may share your information with:\n\n• Other users (public profile and listings)\n• Service providers who help us operate the app\n• Law enforcement when required by law\n\nWe do not sell your personal information to third parties.',
    privacyDataRetentionTitle: 'Data Retention',
    privacyDataRetentionContent: 'We retain your data while your account is active. When you delete your account, your data is removed within 30 days in accordance with GDPR requirements.',
    privacyYourRightsTitle: 'Your Rights',
    privacyYourRightsContent: 'You have the right to:\n\n• Access your personal data\n• Correct inaccurate data\n• Delete your account and data\n• Export your data\n• Opt out of marketing communications',
    privacySecurityTitle: 'Data Security',
    privacySecurityContent: 'We implement appropriate technical and organizational measures to protect your personal information against unauthorized access, alteration, disclosure, or destruction.',
    privacyContactTitle: 'Contact Us',
    privacyContactContent: 'If you have questions about this Privacy Policy or wish to exercise your rights, please contact us at:\n\nprivacy@souqjari.com',
    // Terms of Use
    termsOfUse: 'Terms of Use',
    termsAcceptanceTitle: 'Acceptance of Terms',
    termsAcceptanceContent: 'By accessing or using SouqJari ("the App"), you agree to be bound by these Terms of Use. If you do not agree to these terms, please do not use the App.',
    termsAccountsTitle: 'User Accounts',
    termsAccountsContent: '• You must be at least 18 years old to use the App\n• You are responsible for maintaining the confidentiality of your account\n• You are responsible for all activities under your account\n• You must provide accurate and complete information\n• One person may only maintain one account',
    termsListingRulesTitle: 'Listing Rules',
    termsListingRulesContent: 'When creating listings, you agree to:\n\n• Only list items you own or are authorized to sell\n• Provide accurate descriptions and photos\n• Set fair and honest prices\n• Respond to buyer inquiries in a timely manner\n• Complete transactions in good faith',
    termsProhibitedTitle: 'Prohibited Content',
    termsProhibitedContent: 'The following are strictly prohibited:\n\n• Illegal or stolen items\n• Counterfeit or pirated goods\n• Weapons, drugs, or dangerous materials\n• Adult content or services\n• Fraudulent or misleading listings\n• Spam or unsolicited advertising\n• Content that violates intellectual property rights',
    termsUserConductTitle: 'User Conduct',
    termsUserConductContent: 'You agree not to:\n\n• Harass, threaten, or abuse other users\n• Attempt to circumvent our fees or systems\n• Use the App for any illegal purpose\n• Interfere with the App\'s operation\n• Create multiple accounts',
    termsIPTitle: 'Intellectual Property',
    termsIPContent: 'The App and its original content, features, and functionality are owned by SouqJari and are protected by international copyright, trademark, and other intellectual property laws.',
    termsDisclaimersTitle: 'Disclaimers',
    termsDisclaimersContent: '• SouqJari is a platform for connecting buyers and sellers\n• We do not verify listings or guarantee transactions\n• We are not responsible for the quality of items listed\n• Users transact at their own risk\n• The App is provided "as is" without warranties',
    termsLiabilityTitle: 'Limitation of Liability',
    termsLiabilityContent: 'To the maximum extent permitted by law, SouqJari shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising out of your use of the App.',
    termsTerminationTitle: 'Account Termination',
    termsTerminationContent: 'We reserve the right to suspend or terminate accounts that violate these terms. Users may delete their accounts at any time through the App settings.',
    termsChangesTitle: 'Changes to Terms',
    termsChangesContent: 'We may update these Terms of Use from time to time. Continued use of the App after changes constitutes acceptance of the new terms.',
    termsContactTitle: 'Contact',
    termsContactContent: 'For questions about these Terms of Use, please contact:\n\nlegal@souqjari.com',
  },
  manageAccount: {
    title: 'Manage Account',
    deleteAccountTitle: 'Delete Account',
    deleteAccountWarning: 'Are you sure you want to delete your account? This action cannot be undone. All your listings, messages, and data will be permanently deleted.',
    deleteAccountPermanent: 'This action is permanent',
    deleteAccountPermanentMessage: 'Once you delete your account, all your data including listings, messages, and profile information will be permanently removed and cannot be recovered.',
    typeDeleteToConfirm: 'Type DELETE to confirm',
    typeDeleteExact: 'Please type DELETE exactly as shown',
    enterPasswordToConfirm: 'Enter your password to confirm',
    enterPassword: 'Enter password',
    deleteMyAccount: 'Delete My Account',
    oauthDeleteMessage: 'You signed in with {{provider}}. Type DELETE to confirm account deletion.',
    passwordIncorrect: 'Password is incorrect.',
    deleteError: 'Failed to delete account. Please try again.',
  },
};

export default en;
